// apps/mobile/styles/aiStyles.js
import { StyleSheet } from "react-native";

const C = {
  bg: "#0a0e17",
  bgCard: "rgba(18,22,32,0.9)",
  border: "rgba(255,255,255,0.06)",
  text: "#F3F6FF",
  sub: "#9AA4BC",
  primary: "#7C8CFF",
  primaryDim: "rgba(124,140,255,0.18)",
  danger: "#FF6B6B",
  success: "#5BE49B",
};

export const aiStyles = StyleSheet.create({
  header: {
    marginHorizontal: 18,
    marginTop: 8,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.18)",
    borderRadius: 22,
    backgroundColor: "rgba(10,12,18,0.72)",
  },
  back: {
    width: 44,
    height: 44,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
    alignItems: "center",
    justifyContent: "center",
  },
  titleWrap: { flex: 1 },
  title: { color: C.text, fontSize: 20, fontWeight: "900", letterSpacing: -0.2 },
  statusRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 2 },
  dot: { width: 8, height: 8, borderRadius: 4 },
  statusText: { color: C.sub, fontSize: 12 },
  row: { flexDirection: "row", gap: 9, alignItems: "flex-end", marginVertical: 7 },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: C.border,
  },
  bubble: {
    maxWidth: "78%",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.18)",
  },
  bubbleAI: {
    backgroundColor: "rgba(124,140,255,0.12)",
  },
  bubbleMe: {
    backgroundColor: "rgba(15,23,42,0.82)",
  },
  text: { color: C.text, fontSize: 15, lineHeight: 20 },
  time: { color: C.sub, fontSize: 11, marginTop: 6 },
  composerWrap: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 14,
    backgroundColor: "transparent",
  },
  inputOuter: {
    flex: 1,
    minHeight: 52,
    maxHeight: 140,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.2)",
    backgroundColor: "rgba(15,23,42,0.76)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  input: {
    color: C.text,
    fontSize: 15,
  },
  typing: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 6,
  },
  typingText: { color: C.sub, fontSize: 12 },
  send: {
    backgroundColor: C.primary,
    borderRadius: 18,
    paddingHorizontal: 17,
    paddingVertical: 15,
    alignItems: "center",
    justifyContent: "center",
  },
});

