// apps/mobile/styles/authStyles.js
// Shared styles for login and signup screens
import { StyleSheet } from "react-native";
import { C } from "./theme";

export const authStyles = StyleSheet.create({
  authOrb: {
    position: "absolute",
    top: 34,
    right: -86,
    width: 260,
    height: 260,
    borderRadius: 260,
    backgroundColor: "rgba(99,102,241,0.12)",
  },
  topbar: {
    flexDirection: "column",
    alignItems: "center",
    paddingHorizontal: 22,
    paddingTop: 50,
    gap: 8,
  },
  topActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginTop: 6,
  },
  langBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(0,0,0,0.25)",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  langBtnText: {
    color: C.text,
    fontWeight: "700",
    fontSize: 13,
  },
  settingsBtn: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: "rgba(0,0,0,0.25)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  headerMenu: {
    marginTop: 10,
    minWidth: 178,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.16)",
    backgroundColor: "rgba(15,23,42,0.92)",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
  },
  headerMenuItem: {
    minHeight: 42,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerMenuText: {
    color: C.text,
    fontSize: 13,
    fontWeight: "800",
  },
  headerMenuDivider: {
    height: 1,
    backgroundColor: "rgba(199,210,254,0.12)",
  },
  logoLockup: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  appMark: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.38)",
    backgroundColor: "rgba(99,102,241,0.14)",
  },
  brandWrap: {
    paddingTop: 46,
    alignItems: "center",
    paddingHorizontal: 24,
  },
  logo: { color: C.text, fontSize: 38, fontWeight: "900", letterSpacing: 0.1 },
  tagline: { color: C.sub, textAlign: "center", fontSize: 13 },
  cardWrap: {
    paddingHorizontal: 22,
    marginTop: 30,
  },
  loginCardWrap: {
    marginTop: 115,
  },
  card: {
    borderRadius: 28,
    padding: 20,
    backgroundColor: "rgba(15,23,42,0.78)",
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    overflow: "hidden",
  },
  h1: { color: C.text, fontSize: 27, fontWeight: "900", letterSpacing: -0.3 },
  h2: { color: C.sub, marginTop: 7, marginBottom: 16, lineHeight: 20 },
  inputWrap: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    borderRadius: 18,
    backgroundColor: "rgba(2,6,23,0.34)",
    flexDirection: "row",
    alignItems: "center",
    height: 56,
  },
  smallInputWrap: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    borderRadius: 18,
    backgroundColor: "rgba(2,6,23,0.34)",
    flexDirection: "row",
    alignItems: "center",
    height: 52,
  },
  iconLeft: { paddingLeft: 12, paddingRight: 6 },
  iconRight: { paddingHorizontal: 12, height: "100%", justifyContent: "center" },
  input: {
    flex: 1,
    color: C.text,
    paddingVertical: 10,
    paddingHorizontal: 10,
    fontSize: 16,
  },
  smallInput: {
    flex: 1,
    color: C.text,
    paddingVertical: 6,
    paddingHorizontal: 10,
    fontSize: 14,
  },
  row: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rowLeft: { flexDirection: "row", alignItems: "center", gap: 8 },
  rememberText: { color: C.sub },
  link: {
    color: C.primary,
    fontWeight: "700",
    fontSize: 13,
  },
  btn: {
    marginTop: 18,
    backgroundColor: C.primary,
    paddingVertical: 15,
    borderRadius: 18,
    alignItems: "center",
  },
  btnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "900",
  },
  btnDisabled: {
    opacity: 0.5,
  },
  footer: { color: C.sub, textAlign: "center", marginTop: 48, marginBottom: 14, fontSize: 12 },
  // Signup specific
  label: { color: C.sub, marginTop: 14, marginBottom: 8, fontWeight: "800" },
  roles: { flexDirection: "row", gap: 10 },
  roleChip: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    backgroundColor: "rgba(2,6,23,0.34)",
  },
  roleChipActive: {
    backgroundColor: "rgba(99,102,241,0.2)",
    borderColor: C.primary,
  },
  roleChipText: {
    color: C.text,
    fontSize: 13,
    fontWeight: "700",
  },
  roleChipTextActive: {
    color: C.primary,
  },
  roleText: { color: C.sub, fontWeight: "700" },
  roleTextActive: { color: C.text },
});

