// apps/mobile/styles/cardataStyles.js
import { StyleSheet } from "react-native";
import { colors } from "./theme";

const C = colors.cardata;

export const cardataStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg1 },
  overlay: { flex: 1 },
  topbar: {
    paddingHorizontal: 12,
    paddingTop: 6,
    paddingBottom: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(15,23,42,0.95)",
  },
  topTitle: {
    color: C.text,
    fontSize: 18,
    fontWeight: "800",
  },
  topSubtitle: {
    color: C.sub,
    fontSize: 11,
  },
  linkPill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(15,23,42,0.96)",
  },
  linkDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    marginRight: 6,
  },
  linkDotOn: { backgroundColor: C.ok },
  linkDotOff: { backgroundColor: "#6B7280" },
  linkText: { color: C.sub, fontSize: 11 },
  statusCard: {
    backgroundColor: C.card,
    borderColor: C.border,
    borderWidth: 1,
    borderRadius: 18,
    padding: 12,
    marginHorizontal: 12,
    marginTop: 8,
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  statusRowBottom: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
    flexWrap: "wrap",
  },
  badge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    fontWeight: "800",
    fontSize: 11,
  },
  badgeNormal: {
    backgroundColor: "rgba(34,197,94,0.12)",
    color: C.ok,
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.4)",
  },
  badgeWarning: {
    backgroundColor: "rgba(245,158,11,0.12)",
    color: C.warn,
    borderWidth: 1,
    borderColor: "rgba(245,158,11,0.4)",
  },
  badgeCritical: {
    backgroundColor: "rgba(248,113,113,0.12)",
    color: C.crit,
    borderWidth: 1,
    borderColor: "rgba(248,113,113,0.4)",
  },
  reasonText: {
    color: C.sub,
    flexShrink: 1,
    fontSize: 12,
  },
  advisoryText: {
    color: "#FCA5A5",
    fontSize: 11,
    flexShrink: 1,
  },
  pill: {
    backgroundColor: "rgba(255,255,255,0.04)",
    color: C.text,
    borderWidth: 1,
    borderColor: C.border,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 999,
    fontSize: 11,
  },
  pillOk: {
    backgroundColor: "rgba(34,197,94,0.12)",
    color: C.ok,
    borderColor: "rgba(34,197,94,0.4)",
  },
  pillWarn: {
    backgroundColor: "rgba(245,158,11,0.12)",
    color: C.warn,
    borderColor: "rgba(245,158,11,0.4)",
  },
  actionBar: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 12,
    marginTop: 10,
  },
  actionBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(15,23,42,0.96)",
  },
  actionText: {
    color: C.text,
    fontSize: 12,
    fontWeight: "700",
    marginLeft: 6,
  },
  groupLabel: {
    color: C.sub,
    fontWeight: "700",
    letterSpacing: 0.4,
    marginTop: 16,
    marginLeft: 16,
    fontSize: 12,
  },
  vitalsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
    paddingHorizontal: 12,
  },
  vitalCard: {
    flexGrow: 1,
    flexBasis: "45%",
    backgroundColor: C.cardSoft,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.border,
    padding: 10,
  },
  vitalHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  vitalLabel: {
    color: C.sub,
    fontSize: 11,
  },
  vitalValue: {
    color: C.text,
    fontSize: 18,
    fontWeight: "800",
  },
  tiles: {
    paddingHorizontal: 12,
    marginTop: 8,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  tilesSmall: {
    paddingHorizontal: 12,
    marginTop: 8,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  tile: {
    flexBasis: "47%",
    backgroundColor: C.card,
    borderColor: C.border,
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    gap: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  iconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  mLabel: {
    color: C.sub,
    fontSize: 11,
  },
  mValue: {
    color: C.text,
    fontSize: 16,
    fontWeight: "700",
  },
  barTrack: {
    height: 7,
    borderRadius: 7,
    backgroundColor: "rgba(15,23,42,0.9)",
    overflow: "hidden",
  },
  barFill: {
    height: 7,
  },
  card: {
    backgroundColor: C.card,
    borderColor: C.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 12,
    marginHorizontal: 12,
    marginTop: 8,
  },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  h2: {
    color: C.text,
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 4,
  },
  clearBtn: {
    backgroundColor: C.primary,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  clearBtnText: {
    color: "white",
    fontWeight: "800",
    fontSize: 12,
  },
  chip: {
    backgroundColor: C.chipBg,
    color: "#CFD6FF",
    borderColor: C.chipBorder,
    borderWidth: 1,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    fontSize: 12,
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: C.border,
    backgroundColor: "rgba(8,12,24,0.96)",
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#666",
  },
  dotOn: { backgroundColor: C.ok },
  dotOff: { backgroundColor: "#666" },
  footerText: {
    color: C.sub,
    fontSize: 12,
  },
});

