// apps/mobile/styles/cardataStyles.js
import { StyleSheet } from "react-native";
import { colors } from "./theme";

const C = colors.cardata;

export const cardataStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg1 },
  overlay: { flex: 1 },
  topbar: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    backgroundColor: "rgba(15,23,42,0.72)",
  },
  topTitle: {
    color: C.text,
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
  topSubtitle: {
    color: C.sub,
    fontSize: 11,
  },
  linkPill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    backgroundColor: "rgba(15,23,42,0.72)",
  },
  linkDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    marginRight: 6,
  },
  linkDotOn: { backgroundColor: C.ok },
  linkDotOff: { backgroundColor: "#6B7280" },
  linkText: { color: C.sub, fontSize: 11 },
  statusCard: {
    backgroundColor: "rgba(15,23,42,0.78)",
    borderColor: "rgba(148,163,184,0.25)",
    borderWidth: 1,
    borderRadius: 24,
    padding: 17,
    marginHorizontal: 18,
    marginTop: 10,
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  statusRowBottom: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
    flexWrap: "wrap",
  },
  badge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    fontWeight: "800",
    fontSize: 11,
  },
  badgeNormal: {
    backgroundColor: "rgba(34,197,94,0.12)",
    color: C.ok,
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.4)",
  },
  badgeWarning: {
    backgroundColor: "rgba(245,158,11,0.12)",
    color: C.warn,
    borderWidth: 1,
    borderColor: "rgba(245,158,11,0.4)",
  },
  badgeCritical: {
    backgroundColor: "rgba(248,113,113,0.12)",
    color: C.crit,
    borderWidth: 1,
    borderColor: "rgba(248,113,113,0.4)",
  },
  reasonText: {
    color: C.sub,
    flexShrink: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  advisoryText: {
    color: "#FCA5A5",
    fontSize: 11,
    flexShrink: 1,
  },
  pill: {
    backgroundColor: "rgba(255,255,255,0.04)",
    color: C.text,
    borderWidth: 1,
    borderColor: C.border,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 999,
    fontSize: 11,
  },
  pillOk: {
    backgroundColor: "rgba(34,197,94,0.12)",
    color: C.ok,
    borderColor: "rgba(34,197,94,0.4)",
  },
  pillWarn: {
    backgroundColor: "rgba(245,158,11,0.12)",
    color: C.warn,
    borderColor: "rgba(245,158,11,0.4)",
  },
  actionBar: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 18,
    marginTop: 12,
  },
  actionBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 11,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    backgroundColor: "rgba(15,23,42,0.72)",
  },
  actionText: {
    color: C.text,
    fontSize: 12,
    fontWeight: "800",
    marginLeft: 6,
  },
  groupLabel: {
    color: C.sub,
    fontWeight: "900",
    letterSpacing: 1.1,
    textTransform: "uppercase",
    marginTop: 22,
    marginLeft: 22,
    fontSize: 12,
  },
  vitalsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 10,
    paddingHorizontal: 18,
  },
  vitalCard: {
    flexGrow: 1,
    flexBasis: "45%",
    backgroundColor: "rgba(15,23,42,0.76)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    padding: 13,
  },
  vitalHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  vitalLabel: {
    color: C.sub,
    fontSize: 11,
  },
  vitalValue: {
    color: C.text,
    fontSize: 22,
    fontWeight: "900",
  },
  tiles: {
    paddingHorizontal: 18,
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  tilesSmall: {
    paddingHorizontal: 18,
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  tile: {
    flexBasis: "47%",
    backgroundColor: "rgba(15,23,42,0.76)",
    borderColor: "rgba(148,163,184,0.25)",
    borderWidth: 1,
    borderRadius: 18,
    padding: 12,
    gap: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  iconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  mLabel: {
    color: C.sub,
    fontSize: 11,
  },
  mValue: {
    color: C.text,
    fontSize: 18,
    fontWeight: "900",
  },
  barTrack: {
    height: 7,
    borderRadius: 7,
    backgroundColor: "rgba(15,23,42,0.9)",
    overflow: "hidden",
  },
  barFill: {
    height: 7,
  },
  card: {
    backgroundColor: "rgba(15,23,42,0.78)",
    borderColor: "rgba(148,163,184,0.25)",
    borderWidth: 1,
    borderRadius: 22,
    padding: 16,
    marginHorizontal: 18,
    marginTop: 10,
  },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  h2: {
    color: C.text,
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 4,
  },
  clearBtn: {
    backgroundColor: C.primary,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  clearBtnText: {
    color: "white",
    fontWeight: "800",
    fontSize: 12,
  },
  chip: {
    backgroundColor: C.chipBg,
    color: "#CFD6FF",
    borderColor: C.chipBorder,
    borderWidth: 1,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    fontSize: 12,
  },
  footer: {
    position: "absolute",
    bottom: 10,
    left: 18,
    right: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
    borderRadius: 16,
    backgroundColor: "rgba(8,12,24,0.92)",
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#666",
  },
  dotOn: { backgroundColor: C.ok },
  dotOff: { backgroundColor: "#666" },
  footerText: {
    color: C.sub,
    fontSize: 12,
  },
  sosFab: {
    position: "absolute",
    bottom: 76,
    right: 18,
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#B91C1C",
    borderWidth: 2,
    borderColor: "rgba(254,202,202,0.45)",
    zIndex: 50,
    elevation: 14,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 8,
  },
});

