// apps/mobile/styles/diagnosticsStyles.js
import { StyleSheet } from "react-native";

const C = {
  bg: "#050712",
  card: "rgba(17, 23, 41, 0.96)",
  border: "rgba(148, 163, 184, 0.35)",
  text: "#E5E7EB",
  sub: "#9CA3AF",
  primary: "#7C8CFF",
  ok: "#22C55E",
  warn: "#FACC15",
  crit: "#F97373",
};

export const diagnosticsStyles = StyleSheet.create({
  topbar: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 6,
    flexDirection: "row",
    alignItems: "center",
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(15, 23, 42, 0.75)",
  },
  topTitle: { color: C.text, fontSize: 18, fontWeight: "800" },
  topSubtitle: { color: C.sub, fontSize: 11, marginTop: 2 },
  rightWrap: {
    alignItems: "flex-end",
    gap: 4,
    width: 110,
  },
  adapterText: {
    color: C.sub,
    fontSize: 10,
  },
  dot: { width: 10, height: 10, borderRadius: 999, backgroundColor: "#4B5563" },
  dotOn: { backgroundColor: C.ok },
  dotOff: { backgroundColor: "#4B5563" },
  historyBtn: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(15,23,42,0.9)",
    marginBottom: 2,
  },
  historyText: {
    color: C.text,
    fontSize: 11,
    fontWeight: "700",
    marginLeft: 4,
  },
  card: {
    backgroundColor: C.card,
    borderColor: C.border,
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    marginHorizontal: 12,
    marginTop: 12,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    fontSize: 11,
    fontWeight: "800",
  },
  badgeOk: {
    backgroundColor: "rgba(34,197,94,0.12)",
    color: C.ok,
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.35)",
  },
  badgeWarn: {
    backgroundColor: "rgba(250,204,21,0.12)",
    color: C.warn,
    borderWidth: 1,
    borderColor: "rgba(250,204,21,0.38)",
  },
  badgeInfo: {
    backgroundColor: "rgba(129,140,248,0.12)",
    color: "#A5B4FC",
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.40)",
  },
  pill: {
    backgroundColor: "rgba(15,23,42,0.9)",
    color: C.text,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    fontSize: 11,
  },
  summaryText: {
    marginTop: 10,
    color: C.text,
    fontSize: 13,
    fontWeight: "600",
  },
  helpText: {
    marginTop: 8,
    color: C.sub,
    fontSize: 12,
    lineHeight: 16,
  },
  helpStrong: {
    fontWeight: "700",
    color: C.text,
  },
  actionsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 12,
  },
  mainBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 12,
    justifyContent: "center",
  },
  mainBtnText: {
    color: "#F9FAFB",
    fontWeight: "800",
    fontSize: 13,
  },
  sectionLabel: {
    color: C.sub,
    fontWeight: "700",
    letterSpacing: 0.4,
    marginTop: 16,
    marginLeft: 16,
    fontSize: 12,
  },
  h2: {
    color: C.text,
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 4,
  },
  bodyText: {
    color: C.sub,
    fontSize: 12,
    lineHeight: 16,
  },
  emptyChip: {
    marginTop: 8,
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(15,23,42,0.9)",
    borderWidth: 1,
    borderColor: C.border,
  },
  emptyChipText: {
    color: C.sub,
    fontSize: 12,
  },
  codeRow: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 12,
    padding: 10,
    backgroundColor: "rgba(15,23,42,0.9)",
  },
  codeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "rgba(248,250,252,0.06)",
    borderWidth: 1,
    borderColor: "rgba(209,213,219,0.45)",
    marginRight: 8,
  },
  codeBadgeText: {
    color: "#E5E7EB",
    fontWeight: "800",
    fontSize: 11,
  },
  codeTitle: {
    color: C.text,
    fontSize: 13,
    fontWeight: "700",
    flex: 1,
  },
  codeHint: {
    marginTop: 6,
    color: C.sub,
    fontSize: 11,
    lineHeight: 15,
  },
  rawBox: {
    marginTop: 8,
    marginBottom: 6,
    padding: 8,
    borderRadius: 8,
    backgroundColor: "rgba(15,23,42,0.9)",
    borderWidth: 1,
    borderColor: C.border,
    color: "#E5E7EB",
    fontSize: 12,
    fontFamily: "monospace",
  },
});

