// apps/mobile/styles/diagnosticsStyles.js
import { StyleSheet } from "react-native";

const C = {
  bg: "#050712",
  card: "rgba(17, 23, 41, 0.96)",
  border: "rgba(148, 163, 184, 0.35)",
  text: "#E5E7EB",
  sub: "#9CA3AF",
  primary: "#7C8CFF",
  ok: "#22C55E",
  warn: "#FACC15",
  crit: "#F97373",
};

export const diagnosticsStyles = StyleSheet.create({
  topbar: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  backBtn: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    backgroundColor: "rgba(15, 23, 42, 0.72)",
  },
  topTitle: { color: C.text, fontSize: 20, fontWeight: "900", letterSpacing: -0.2 },
  topSubtitle: { color: C.sub, fontSize: 11, marginTop: 2 },
  rightWrap: {
    alignItems: "flex-end",
    gap: 4,
    width: 122,
  },
  adapterText: {
    color: C.sub,
    fontSize: 10,
  },
  dot: { width: 10, height: 10, borderRadius: 999, backgroundColor: "#4B5563" },
  dotOn: { backgroundColor: C.ok },
  dotOff: { backgroundColor: "#4B5563" },
  historyBtn: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    backgroundColor: "rgba(15,23,42,0.72)",
    marginBottom: 2,
  },
  historyText: {
    color: C.text,
    fontSize: 11,
    fontWeight: "700",
    marginLeft: 4,
  },
  card: {
    backgroundColor: "rgba(15,23,42,0.78)",
    borderColor: "rgba(148,163,184,0.25)",
    borderWidth: 1,
    borderRadius: 24,
    padding: 17,
    marginHorizontal: 18,
    marginTop: 14,
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  badge: {
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 999,
    fontSize: 11,
    fontWeight: "800",
  },
  badgeOk: {
    backgroundColor: "rgba(34,197,94,0.12)",
    color: C.ok,
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.35)",
  },
  badgeWarn: {
    backgroundColor: "rgba(250,204,21,0.12)",
    color: C.warn,
    borderWidth: 1,
    borderColor: "rgba(250,204,21,0.38)",
  },
  badgeInfo: {
    backgroundColor: "rgba(129,140,248,0.12)",
    color: "#A5B4FC",
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.40)",
  },
  pill: {
    backgroundColor: "rgba(2,6,23,0.36)",
    color: C.text,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    fontSize: 11,
  },
  summaryText: {
    marginTop: 14,
    color: C.text,
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 21,
  },
  helpText: {
    marginTop: 8,
    color: C.sub,
    fontSize: 12,
    lineHeight: 16,
  },
  helpStrong: {
    fontWeight: "700",
    color: C.text,
  },
  actionsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 16,
  },
  mainBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 13,
    paddingHorizontal: 12,
    borderRadius: 16,
    justifyContent: "center",
  },
  mainBtnText: {
    color: "#F9FAFB",
    fontWeight: "800",
    fontSize: 14,
  },
  sectionLabel: {
    color: C.sub,
    fontWeight: "900",
    letterSpacing: 1.1,
    textTransform: "uppercase",
    marginTop: 20,
    marginLeft: 22,
    fontSize: 12,
  },
  h2: {
    color: C.text,
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 6,
  },
  bodyText: {
    color: C.sub,
    fontSize: 12,
    lineHeight: 16,
  },
  emptyChip: {
    marginTop: 8,
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(2,6,23,0.32)",
    borderWidth: 1,
    borderColor: C.border,
  },
  emptyChipText: {
    color: C.sub,
    fontSize: 12,
  },
  codeRow: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 16,
    padding: 12,
    backgroundColor: "rgba(2,6,23,0.32)",
  },
  codeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "rgba(248,250,252,0.06)",
    borderWidth: 1,
    borderColor: "rgba(209,213,219,0.45)",
    marginRight: 8,
  },
  codeBadgeText: {
    color: "#E5E7EB",
    fontWeight: "800",
    fontSize: 11,
  },
  codeTitle: {
    color: C.text,
    fontSize: 13,
    fontWeight: "700",
    flex: 1,
  },
  codeHint: {
    marginTop: 6,
    color: C.sub,
    fontSize: 11,
    lineHeight: 15,
  },
  rawBox: {
    marginTop: 8,
    marginBottom: 6,
    padding: 8,
    borderRadius: 14,
    backgroundColor: "rgba(2,6,23,0.34)",
    borderWidth: 1,
    borderColor: C.border,
    color: "#E5E7EB",
    fontSize: 12,
    fontFamily: "monospace",
  },
  filterCard: {
    marginBottom: 10,
    paddingBottom: 14,
  },
  filterHelp: {
    color: C.sub,
    fontSize: 11,
    lineHeight: 15,
    marginBottom: 10,
  },
  searchInput: {
    backgroundColor: "rgba(2,6,23,0.45)",
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    color: C.text,
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 12,
  },
  chipScrollContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingRight: 8,
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.35)",
    backgroundColor: "rgba(15,23,42,0.55)",
  },
  filterChipActive: {
    borderColor: "rgba(129,140,248,0.55)",
    backgroundColor: "rgba(99,102,241,0.2)",
  },
  filterChipText: {
    color: C.sub,
    fontSize: 11,
    fontWeight: "700",
  },
  filterChipTextActive: {
    color: "#E0E7FF",
  },
  severityPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
  },
  severityPillText: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  categoryPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.35)",
    backgroundColor: "rgba(2,6,23,0.35)",
  },
  categoryPillText: {
    color: C.sub,
    fontSize: 9,
    fontWeight: "700",
  },
  codeDetail: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(148,163,184,0.2)",
  },
  aiSummaryBox: {
    marginBottom: 12,
    padding: 10,
    borderRadius: 12,
    backgroundColor: "rgba(99,102,241,0.1)",
    borderWidth: 1,
    borderColor: "rgba(165,180,252,0.28)",
  },
  aiSummaryText: {
    color: "#E0E7FF",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
  },
  detailSectionLabel: {
    color: "#A5B4FC",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  detailBody: {
    color: C.sub,
    fontSize: 12,
    lineHeight: 17,
  },
  detailBodyStrong: {
    color: C.text,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
  },
  bulletLine: {
    color: C.sub,
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 2,
  },
});

