// apps/mobile/styles/doctorCarStyles.js — DoctorCar AI premium cockpit theme
import { StyleSheet, Platform } from "react-native";

export const DC = {
  bg: "#030712",
  card: "rgba(15,23,42,0.85)",
  glass: "rgba(17,24,39,0.72)",
  glow: "rgba(56,189,248,0.25)",
  cyan: "#22D3EE",
  cyanDim: "rgba(34,211,238,0.65)",
  violet: "#A78BFA",
  green: "#34D399",
  amber: "#FBBF24",
  red: "#F87171",
  text: "#F8FAFC",
  sub: "#94A3B8",
  border: "rgba(148,163,184,0.14)",
  borderGlow: "rgba(56,189,248,0.35)",
};

export const doctorCarStyles = StyleSheet.create({
  rootFade: {
    flex: 1,
  },

  topbar: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 16,
    paddingBottom: 8,
    gap: 12,
    zIndex: 2,
  },
  topbarGlow: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: 120,
    opacity: 0.35,
  },
  backBtn: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.92)",
    borderWidth: 1,
    borderColor: DC.border,
  },
  brandBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "rgba(34,211,238,0.08)",
    borderWidth: 1,
    borderColor: "rgba(34,211,238,0.28)",
    marginBottom: 8,
  },
  brandBadgeText: {
    color: DC.cyan,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.8,
  },
  titleXL: {
    color: DC.text,
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: -0.5,
  },
  subtitleSm: {
    color: DC.sub,
    fontSize: 13,
    marginTop: 6,
    lineHeight: 19,
    fontWeight: "500",
    maxWidth: "92%",
  },

  heroWrap: {
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.28)",
  },
  heroGradientBg: {
    borderRadius: 24,
    padding: 2,
  },
  heroInnerDark: {
    borderRadius: 22,
    paddingVertical: 24,
    paddingHorizontal: 18,
    backgroundColor: "rgba(7,11,22,0.94)",
    alignItems: "center",
  },
  heroRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: 4,
    gap: 16,
  },
  scoreRingOuter: {
    width: 132,
    height: 132,
    borderRadius: 66,
    padding: 3,
    justifyContent: "center",
    alignItems: "center",
  },
  scoreRingInner: {
    flex: 1,
    width: "100%",
    borderRadius: 63,
    backgroundColor: "rgba(6,8,18,0.98)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.12)",
  },
  scoreHuge: {
    fontSize: 44,
    fontWeight: "900",
    color: DC.text,
    letterSpacing: -2,
  },
  scoreOutOf: {
    fontSize: 11,
    fontWeight: "700",
    color: DC.sub,
    marginTop: 2,
    letterSpacing: 1,
  },
  scoreLabel: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: "800",
    color: DC.sub,
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  heroMetaCol: {
    flex: 1,
    minWidth: 140,
    gap: 10,
  },
  bandPill: {
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(52,211,153,0.35)",
    backgroundColor: "rgba(52,211,153,0.08)",
  },
  bandText: {
    color: DC.green,
    fontWeight: "800",
    fontSize: 11,
    letterSpacing: 0.9,
    textTransform: "uppercase",
  },
  liveRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: DC.green,
  },
  liveDotIdle: {
    backgroundColor: DC.sub,
  },
  liveCaption: {
    color: DC.sub,
    fontSize: 11,
    fontWeight: "600",
    flex: 1,
  },
  updatedStamp: {
    color: "rgba(148,163,184,0.75)",
    fontSize: 10,
    fontWeight: "600",
    marginTop: 4,
  },

  summaryCard: {
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 18,
    borderRadius: 18,
    backgroundColor: DC.glass,
    borderWidth: 1,
    borderColor: DC.border,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.35,
        shadowRadius: 20,
      },
      android: { elevation: 6 },
    }),
  },
  summaryText: {
    color: DC.text,
    fontSize: 15,
    lineHeight: 23,
    fontWeight: "600",
  },
  disclaimer: {
    marginTop: 12,
    color: DC.sub,
    fontSize: 11,
    lineHeight: 17,
  },

  clusterRow: {
    flexDirection: "row",
    marginHorizontal: 16,
    marginBottom: 14,
    gap: 10,
  },
  clusterTile: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: "rgba(15,23,42,0.75)",
    borderWidth: 1,
    borderColor: DC.border,
  },
  clusterTileLabel: {
    color: DC.sub,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  clusterTileValue: {
    color: DC.text,
    fontSize: 13,
    fontWeight: "800",
  },

  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginBottom: 10,
    marginTop: 10,
    gap: 10,
  },
  sectionRule: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(148,163,184,0.15)",
    marginLeft: 4,
  },
  sectionIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34,211,238,0.1)",
    borderWidth: 1,
    borderColor: "rgba(34,211,238,0.22)",
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1.6,
    color: DC.cyan,
    textTransform: "uppercase",
  },

  insightCard: {
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 16,
    borderRadius: 18,
    backgroundColor: DC.glass,
    borderWidth: 1,
    borderColor: DC.border,
    borderLeftWidth: 3,
    borderLeftColor: "rgba(56,189,248,0.55)",
  },
  insightLabel: {
    color: DC.text,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 22,
  },
  analysisCard: {
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 16,
    borderRadius: 18,
    backgroundColor: "rgba(10,14,26,0.88)",
    borderWidth: 1,
    borderColor: "rgba(167,139,250,0.22)",
  },
  analysisLine: {
    color: DC.text,
    fontSize: 13,
    lineHeight: 22,
    marginBottom: 10,
    fontWeight: "500",
    paddingLeft: 12,
    borderLeftWidth: 2,
    borderLeftColor: "rgba(167,139,250,0.45)",
  },

  recPrimaryTag: {
    color: DC.cyan,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  recPrimary: {
    color: DC.text,
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 23,
  },
  recSecondary: {
    marginTop: 8,
    color: DC.sub,
    fontSize: 13,
    lineHeight: 21,
    fontWeight: "600",
  },

  vitalsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: 12,
    gap: 10,
    marginBottom: 14,
  },
  vitalTile: {
    width: Platform.OS === "web" ? "31%" : "47%",
    flexGrow: 1,
    minWidth: 148,
    padding: 14,
    borderRadius: 16,
    backgroundColor: "rgba(15,23,42,0.82)",
    borderWidth: 1,
    borderColor: "rgba(56,189,248,0.18)",
  },
  vitalTileHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  vitalLabel: {
    color: DC.sub,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.7,
    textTransform: "uppercase",
    flex: 1,
  },
  vitalValue: {
    color: DC.text,
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: -0.5,
  },

  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginHorizontal: 16,
    marginBottom: 14,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(251,191,36,0.28)",
    backgroundColor: "rgba(251,191,36,0.06)",
    maxWidth: "100%",
  },
  chipCrit: {
    borderColor: "rgba(248,113,113,0.45)",
    backgroundColor: "rgba(248,113,113,0.09)",
  },
  chipText: {
    color: DC.amber,
    fontSize: 12,
    fontWeight: "700",
    flexShrink: 1,
    lineHeight: 17,
  },
  chipTextCrit: {
    color: DC.red,
  },

  dtcCard: {
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 18,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(167,139,250,0.25)",
    backgroundColor: "rgba(15,23,42,0.88)",
  },
  dtcCardAccent: {
    height: 3,
    width: "100%",
  },
  dtcCardBody: {
    padding: 16,
  },
  dtcCode: {
    color: DC.violet,
    fontWeight: "900",
    fontSize: 17,
    letterSpacing: 1.2,
  },
  dtcSev: {
    marginTop: 6,
    fontSize: 10,
    fontWeight: "800",
    color: DC.sub,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  dtcBody: {
    marginTop: 10,
    color: DC.text,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "500",
  },
  dtcAiBanner: {
    marginTop: 12,
    padding: 10,
    borderRadius: 12,
    backgroundColor: "rgba(99,102,241,0.12)",
    borderWidth: 1,
    borderColor: "rgba(165,180,252,0.28)",
  },
  dtcAiLabel: {
    color: "#A5B4FC",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.6,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  dtcAiText: {
    color: "#E0E7FF",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
  },
  dtcCanDriveLine: {
    marginTop: 12,
    color: DC.amber,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 18,
  },
  dtcInlineStrong: {
    color: DC.text,
    fontWeight: "900",
  },
  dtcSubLabel: {
    color: DC.sub,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  dtcBullet: {
    color: DC.sub,
    fontSize: 11,
    lineHeight: 17,
    marginBottom: 2,
  },
  dtcRecAction: {
    marginTop: 12,
    color: DC.text,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
  },

  emptyHint: {
    marginHorizontal: 16,
    padding: 22,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: DC.border,
    borderStyle: "dashed",
    backgroundColor: "rgba(15,23,42,0.5)",
  },
  emptyText: {
    color: DC.sub,
    fontSize: 14,
    lineHeight: 22,
    textAlign: "center",
  },
  linkBtn: {
    marginTop: 14,
    alignSelf: "center",
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: "rgba(99,102,241,0.22)",
    borderWidth: 1,
    borderColor: "rgba(165,180,252,0.4)",
  },
  linkBtnText: {
    color: "#E0E7FF",
    fontWeight: "900",
    fontSize: 13,
    letterSpacing: 0.3,
  },

  footNote: {
    marginHorizontal: 20,
    marginTop: 12,
    marginBottom: 36,
    fontSize: 10,
    color: "rgba(148,163,184,0.75)",
    lineHeight: 16,
    textAlign: "center",
  },

  statusRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: 16,
    marginBottom: 6,
    gap: 10,
    alignItems: "center",
  },
  statusPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
  },
  statusPillLive: {
    borderColor: "rgba(52,211,153,0.45)",
    backgroundColor: "rgba(52,211,153,0.1)",
  },
  statusPillIdle: {
    borderColor: "rgba(148,163,184,0.3)",
    backgroundColor: "rgba(15,23,42,0.75)",
  },
  statusPillText: {
    color: DC.text,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  riskBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 14,
    borderWidth: 1,
  },
  riskBadgeText: {
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.35,
    color: DC.text,
  },
  risk_low: {
    borderColor: "rgba(52,211,153,0.35)",
    backgroundColor: "rgba(52,211,153,0.08)",
  },
  risk_moderate: {
    borderColor: "rgba(251,191,36,0.45)",
    backgroundColor: "rgba(251,191,36,0.1)",
  },
  risk_high: {
    borderColor: "rgba(251,146,60,0.55)",
    backgroundColor: "rgba(251,146,60,0.12)",
  },
  risk_severe: {
    borderColor: "rgba(248,113,113,0.55)",
    backgroundColor: "rgba(248,113,113,0.14)",
  },

  heroOuter: {},
  heroInner: {},
});
