// apps/mobile/styles/forgotpasswordStyles.js
import { StyleSheet } from "react-native";

const C = {
  text: "#E6E9F5",
  sub: "#A8B2D1",
  primary: "#7C8CFF",
  border: "rgba(255,255,255,.12)",
  glass: "rgba(18,22,33,.72)",
};

export const forgotpasswordStyles = StyleSheet.create({
  authOrb: {
    position: "absolute",
    top: 34,
    right: -86,
    width: 260,
    height: 260,
    borderRadius: 260,
    backgroundColor: "rgba(99,102,241,0.12)",
  },
  topbar: {
    paddingHorizontal: 22,
    paddingTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: "rgba(15,23,42,0.72)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  logoLockup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  appMark: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.38)",
    backgroundColor: "rgba(99,102,241,0.14)",
  },
  brandWrap: { paddingTop: 8, alignItems: "center" },
  logo: { color: C.text, fontSize: 28, fontWeight: "900", letterSpacing: 0.2 },
  tagline: { color: C.sub, marginTop: 2, textAlign: "center", fontSize: 13 },
  cardWrap: { flex: 1, justifyContent: "center", paddingHorizontal: 22 },
  card: {
    borderRadius: 28,
    padding: 20,
    backgroundColor: "rgba(15,23,42,0.78)",
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    overflow: "hidden",
  },
  h1: { color: C.text, fontSize: 27, fontWeight: "900", letterSpacing: -0.3 },
  h2: { color: C.sub, marginTop: 7, marginBottom: 16, lineHeight: 20 },
  inputWrap: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    borderRadius: 18,
    backgroundColor: "rgba(2,6,23,0.34)",
    flexDirection: "row",
    alignItems: "center",
    height: 56,
  },
  iconLeft: { paddingLeft: 12, paddingRight: 6 },
  input: {
    flex: 1,
    color: C.text,
    paddingVertical: 10,
    paddingHorizontal: 10,
    fontSize: 16,
  },
  btn: {
    marginTop: 18,
    backgroundColor: C.primary,
    borderRadius: 18,
    alignItems: "center",
    paddingVertical: 15,
  },
  btnText: { color: "#fff", fontWeight: "900", fontSize: 16 },
  link: { color: C.primary, fontWeight: "800" },
});

