// apps/mobile/styles/forumStyles.js
import { StyleSheet, Platform } from "react-native";
import { C } from "./theme";

export const forumStyles = StyleSheet.create({
  forumHero: {
    marginHorizontal: 18,
    marginBottom: 18,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    padding: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  heroGlow: {
    position: "absolute",
    top: -90,
    right: -70,
    width: 210,
    height: 210,
    borderRadius: 210,
    backgroundColor: "rgba(129,140,248,0.2)",
  },
  topbar: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 16,
    gap: 12,
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.72)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
  },
  headerTitle: {
    flex: 1,
    color: C.text,
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: -0.3,
  },
  headerSub: {
    color: C.sub,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  eyebrow: {
    color: C.primary,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2,
    marginBottom: 4,
  },
  searchOuter: {
    marginBottom: 14,
    borderRadius: 22,
    padding: 1.5,
    overflow: "hidden",
    backgroundColor: "rgba(129,140,248,0.18)",
  },
  searchInner: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === "ios" ? 13 : 11,
    borderRadius: 19,
    backgroundColor: "rgba(2,6,23,0.36)",
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
  },
  searchInput: {
    flex: 1,
    color: C.text,
    fontSize: 15,
    marginLeft: 8,
  },
  chipScroll: {
    marginBottom: 10,
    paddingLeft: 0,
    maxHeight: 48,
  },
  chip: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 999,
    marginRight: 8,
    backgroundColor: "rgba(2,6,23,0.34)",
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.16)",
  },
  chipActive: {
    borderColor: "rgba(99,102,241,0.65)",
    backgroundColor: "rgba(99,102,241,0.28)",
  },
  chipText: {
    color: C.sub,
    fontSize: 12,
    fontWeight: "700",
  },
  chipTextActive: {
    color: C.text,
  },
  sortRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 0,
    marginBottom: 0,
  },
  sortChip: {
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "rgba(2,6,23,0.3)",
    borderWidth: 1,
    borderColor: "rgba(59,130,246,0.25)",
  },
  sortChipActive: {
    borderColor: "rgba(34,197,94,0.45)",
    backgroundColor: "rgba(34,197,94,0.12)",
  },
  sortChipText: {
    color: C.sub,
    fontSize: 11,
    fontWeight: "700",
  },
  sortChipTextActive: {
    color: "#86EFAC",
  },
  postCard: {
    marginHorizontal: 22,
    marginBottom: 14,
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.24)",
    backgroundColor: "rgba(15,23,42,0.74)",
  },
  postCardInner: {
    padding: 16,
  },
  catBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "rgba(99,102,241,0.18)",
    marginBottom: 8,
  },
  catBadgeText: {
    color: "#A5B4FC",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  dtcBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "rgba(251,191,36,0.15)",
    borderWidth: 1,
    borderColor: "rgba(251,191,36,0.45)",
    marginBottom: 8,
  },
  dtcBadgeText: {
    color: "#FDE68A",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  statusOpen: {
    color: "#93C5FD",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  statusSolved: {
    color: "#86EFAC",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  postTitle: {
    color: C.text,
    fontSize: 19,
    fontWeight: "900",
    letterSpacing: -0.2,
    marginBottom: 6,
  },
  postMeta: {
    color: C.sub,
    fontSize: 12,
    marginBottom: 8,
  },
  postPreview: {
    color: C.sub,
    fontSize: 13,
    lineHeight: 19,
  },
  postFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "rgba(148,163,184,0.12)",
  },
  statRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  statText: {
    color: C.sub,
    fontSize: 12,
    fontWeight: "600",
  },
  fab: {
    position: "absolute",
    right: 18,
    bottom: 28,
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#6366F1",
    borderWidth: 2,
    borderColor: "rgba(165,180,252,0.45)",
    elevation: 10,
    zIndex: 20,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 8,
  },
  centerMsg: {
    padding: 40,
    alignItems: "center",
  },
  centerText: {
    color: C.sub,
    fontSize: 14,
    textAlign: "center",
    lineHeight: 21,
  },
  inputBlock: {
    marginHorizontal: 14,
    marginBottom: 14,
  },
  label: {
    color: C.sub,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 8,
    letterSpacing: 0.4,
  },
  textInput: {
    backgroundColor: "rgba(15,23,42,0.94)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.22)",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: C.text,
    fontSize: 15,
  },
  textArea: {
    minHeight: 120,
    textAlignVertical: "top",
  },
  submitBtn: {
    marginHorizontal: 14,
    marginTop: 8,
    marginBottom: 28,
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: "center",
    backgroundColor: "#6366F1",
    borderWidth: 1,
    borderColor: "rgba(165,180,252,0.35)",
  },
  submitBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "900",
  },
  errorText: {
    color: "#FCA5A5",
    fontSize: 13,
    marginHorizontal: 14,
    marginBottom: 8,
  },
  commentBox: {
    marginHorizontal: 14,
    marginTop: 12,
    padding: 14,
    borderRadius: 16,
    backgroundColor: "rgba(15,23,42,0.92)",
    borderWidth: 1,
    borderColor: "rgba(59,130,246,0.15)",
  },
  commentAuthor: {
    color: C.text,
    fontWeight: "800",
    fontSize: 14,
    marginBottom: 6,
  },
  commentBody: {
    color: C.sub,
    fontSize: 14,
    lineHeight: 21,
  },
  solutionRibbon: {
    alignSelf: "flex-start",
    marginBottom: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: "rgba(34,197,94,0.2)",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.45)",
  },
  solutionRibbonText: {
    color: "#86EFAC",
    fontSize: 10,
    fontWeight: "900",
  },
  roleBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    alignSelf: "flex-start",
  },
  roleBadge_client: {
    backgroundColor: "rgba(148,163,184,0.12)",
    borderColor: "rgba(148,163,184,0.35)",
  },
  roleBadge_garage: {
    backgroundColor: "rgba(251,191,36,0.12)",
    borderColor: "rgba(251,191,36,0.45)",
  },
  roleBadge_admin: {
    backgroundColor: "rgba(99,102,241,0.18)",
    borderColor: "rgba(129,140,248,0.45)",
  },
  roleBadgeText: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  roleBadgeText_client: {
    color: "#94A3B8",
  },
  roleBadgeText_garage: {
    color: "#FCD34D",
  },
  roleBadgeText_admin: {
    color: "#A5B4FC",
  },
  postThumb: {
    width: "100%",
    height: 180,
    borderRadius: 14,
    marginTop: 12,
    backgroundColor: "rgba(15,23,42,0.8)",
  },
  postThumbList: {
    width: "100%",
    height: 110,
    borderRadius: 12,
    marginTop: 10,
    backgroundColor: "rgba(15,23,42,0.8)",
  },
  authorRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 6,
  },
});
