// apps/mobile/styles/garageStyles.js
import { StyleSheet } from "react-native";
import { C } from "./theme";

export const garageStyles = StyleSheet.create({
  bg: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(148,163,184,0.15)",
  },
  appIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  logoCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(250,204,21,0.15)",
    borderWidth: 1,
    borderColor: "rgba(250,204,21,0.35)",
    justifyContent: "center",
    alignItems: "center",
  },
  appTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: C.text,
    letterSpacing: 0.3,
  },
  appSubtitle: {
    fontSize: 12,
    color: C.sub,
    marginTop: 2,
  },
  langChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  langChipText: {
    fontSize: 12,
    color: C.text,
    fontWeight: "600",
  },
  profileBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  welcomeCard: {
    backgroundColor: "rgba(15,23,42,0.95)",
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(250,204,21,0.2)",
  },
  welcomeTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: C.text,
    marginBottom: 8,
  },
  welcomeText: {
    fontSize: 14,
    color: C.sub,
    lineHeight: 20,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 24,
  },
  statCard: {
    width: "47%",
    backgroundColor: "rgba(15,23,42,0.95)",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.15)",
    alignItems: "center",
  },
  statIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    borderWidth: 1,
  },
  statValue: {
    fontSize: 24,
    fontWeight: "800",
    color: C.text,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: C.sub,
    textAlign: "center",
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: C.text,
    marginBottom: 12,
  },
  actionsList: {
    gap: 12,
  },
  actionCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(15,23,42,0.95)",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.15)",
    gap: 16,
  },
  actionIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
  },
  actionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: C.text,
    marginBottom: 4,
  },
  actionSubtitle: {
    fontSize: 13,
    color: C.sub,
    lineHeight: 18,
  },
  toolsList: {
    gap: 10,
  },
  toolRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(15,23,42,0.95)",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.15)",
    gap: 12,
  },
  toolIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(124,140,255,0.15)",
    borderWidth: 1,
    borderColor: "rgba(124,140,255,0.35)",
    justifyContent: "center",
    alignItems: "center",
  },
  toolTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: C.text,
    marginBottom: 2,
  },
  toolDesc: {
    fontSize: 12,
    color: C.sub,
  },
  footer: {
    textAlign: "center",
    color: C.sub,
    fontSize: 12,
    marginTop: 20,
  },
});


