// Full-screen garage listing editor — spacious layout
import { StyleSheet } from "react-native";
import { C } from "./theme";

export const garageLocationScreenStyles = StyleSheet.create({
  flex: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(148,163,184,0.12)",
  },
  backBtn: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitleBlock: {
    flex: 1,
    paddingRight: 44,
  },
  headerTitle: {
    fontSize: 19,
    fontWeight: "900",
    color: C.text,
    letterSpacing: 0.2,
  },
  headerSubtitle: {
    fontSize: 12,
    color: C.sub,
    marginTop: 3,
    lineHeight: 16,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 36,
  },
  pageIntro: {
    fontSize: 15,
    color: C.sub,
    lineHeight: 23,
    marginBottom: 22,
  },
  sectionCard: {
    backgroundColor: "rgba(15,23,42,0.92)",
    borderRadius: 20,
    padding: 22,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.14)",
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "900",
    color: C.text,
    marginBottom: 6,
  },
  sectionHint: {
    fontSize: 14,
    color: C.sub,
    lineHeight: 21,
    marginBottom: 18,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: "800",
    color: C.sub,
    marginBottom: 10,
    marginTop: 4,
    letterSpacing: 0.2,
  },
  input: {
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.04)",
    color: C.text,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
  },
  textArea: {
    minHeight: 104,
    textAlignVertical: "top",
  },
  textAreaTall: {
    minHeight: 128,
    textAlignVertical: "top",
  },
  helpBox: {
    marginTop: 18,
    marginBottom: 6,
    padding: 16,
    borderRadius: 14,
    backgroundColor: "rgba(99,102,241,0.1)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.22)",
  },
  helpBoxText: {
    fontSize: 13,
    lineHeight: 20,
    color: C.sub,
  },
  row2: {
    flexDirection: "row",
    gap: 14,
    marginTop: 4,
  },
  row2Item: {
    flex: 1,
    minWidth: 0,
  },
  primaryAction: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: 18,
    paddingVertical: 15,
    paddingHorizontal: 18,
    borderRadius: 16,
    backgroundColor: "rgba(99,102,241,0.22)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.45)",
  },
  primaryActionText: {
    color: C.primary,
    fontSize: 16,
    fontWeight: "800",
  },
  secondaryAction: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: 12,
    paddingVertical: 15,
    paddingHorizontal: 18,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  secondaryActionText: {
    color: C.primary,
    fontSize: 16,
    fontWeight: "800",
  },
  saveBar: {
    marginTop: 8,
    paddingTop: 8,
  },
  saveBtn: {
    marginTop: 12,
    paddingVertical: 16,
    borderRadius: 16,
    backgroundColor: C.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  saveBtnText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "900",
  },
  spacerSm: { height: 8 },
  spacerMd: { height: 16 },
});
