// Full-screen garage listing editor — spacious layout
import { StyleSheet } from "react-native";
import { C } from "./theme";

export const garageLocationScreenStyles = StyleSheet.create({
  flex: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 13,
  },
  backBtn: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "rgba(15,23,42,0.72)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  headerEyebrow: {
    color: C.primary,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.3,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: C.text,
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    fontSize: 12,
    color: C.sub,
    marginTop: 3,
    lineHeight: 16,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 22,
    paddingTop: 10,
    paddingBottom: 36,
  },
  heroPanel: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    padding: 18,
    marginBottom: 22,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  heroGlow: {
    position: "absolute",
    top: -90,
    right: -70,
    width: 210,
    height: 210,
    borderRadius: 210,
    backgroundColor: "rgba(129,140,248,0.2)",
  },
  pageIntro: {
    fontSize: 15,
    color: C.sub,
    lineHeight: 23,
    marginTop: 16,
  },
  sectionCard: {
    backgroundColor: "rgba(15,23,42,0.78)",
    borderRadius: 24,
    padding: 18,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "900",
    color: C.text,
    marginBottom: 14,
  },
  sectionHint: {
    fontSize: 14,
    color: C.sub,
    lineHeight: 21,
    marginBottom: 18,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: "800",
    color: C.sub,
    marginBottom: 10,
    marginTop: 8,
    letterSpacing: 0.2,
  },
  input: {
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
    borderRadius: 18,
    backgroundColor: "rgba(2,6,23,0.34)",
    color: C.text,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
  },
  textArea: {
    minHeight: 104,
    textAlignVertical: "top",
  },
  textAreaTall: {
    minHeight: 128,
    textAlignVertical: "top",
  },
  helpBox: {
    marginTop: 18,
    marginBottom: 6,
    padding: 16,
    borderRadius: 18,
    backgroundColor: "rgba(99,102,241,0.1)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.22)",
  },
  helpBoxText: {
    fontSize: 13,
    lineHeight: 20,
    color: C.sub,
  },
  row2: {
    flexDirection: "row",
    gap: 14,
    marginTop: 14,
  },
  row2Item: {
    flex: 1,
    minWidth: 0,
  },
  primaryAction: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: 18,
    paddingVertical: 15,
    paddingHorizontal: 18,
    borderRadius: 18,
    backgroundColor: "rgba(99,102,241,0.22)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.45)",
  },
  primaryActionText: {
    color: C.primary,
    fontSize: 16,
    fontWeight: "800",
  },
  secondaryAction: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: 12,
    paddingVertical: 15,
    paddingHorizontal: 18,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
    backgroundColor: "rgba(2,6,23,0.28)",
  },
  secondaryActionText: {
    color: C.primary,
    fontSize: 16,
    fontWeight: "800",
  },
  saveBar: {
    marginTop: 8,
    paddingTop: 8,
  },
  saveBtn: {
    marginTop: 12,
    paddingVertical: 16,
    borderRadius: 18,
    backgroundColor: C.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  saveBtnText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "900",
  },
  spacerSm: { height: 8 },
  spacerMd: { height: 16 },
});
