// apps/mobile/styles/garageStyles.js
import { StyleSheet } from "react-native";
import { C } from "./theme";

export const garageStyles = StyleSheet.create({
  bg: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 22,
    paddingTop: 10,
    paddingBottom: 8,
  },
  appIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    flex: 1,
    marginRight: 14,
  },
  logoCircle: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: "rgba(99,102,241,0.14)",
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.45)",
    justifyContent: "center",
    alignItems: "center",
  },
  appTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  appTitle: {
    fontSize: 23,
    fontWeight: "900",
    color: C.text,
    letterSpacing: 0.1,
  },
  appSubtitle: {
    fontSize: 13,
    color: C.sub,
    marginTop: 2,
    lineHeight: 17,
    opacity: 0.95,
  },
  langChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "rgba(2,6,23,0.36)",
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    maxWidth: 136,
  },
  langChipText: {
    fontSize: 13,
    color: C.text,
    fontWeight: "700",
    flexShrink: 1,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    flexShrink: 0,
  },
  profileBtn: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: "rgba(15,23,42,0.72)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.28)",
    justifyContent: "center",
    alignItems: "center",
  },
  logoutBtn: {
    backgroundColor: "rgba(249,115,115,0.12)",
    borderColor: "rgba(249,115,115,0.34)",
  },
  content: {
    paddingHorizontal: 22,
    paddingTop: 10,
    paddingBottom: 116,
  },
  heroPanel: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    padding: 18,
    marginBottom: 26,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  heroGlow: {
    position: "absolute",
    top: -90,
    right: -70,
    width: 210,
    height: 210,
    borderRadius: 210,
    backgroundColor: "rgba(129,140,248,0.2)",
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
  },
  welcomeEyebrow: {
    color: "#C7D2FE",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.3,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  welcomeTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: C.text,
    letterSpacing: -0.3,
  },
  welcomeText: {
    fontSize: 14,
    color: C.sub,
    lineHeight: 21,
    marginTop: 10,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 18,
  },
  statCard: {
    flexBasis: "47%",
    flexGrow: 1,
    backgroundColor: "rgba(2,6,23,0.34)",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.16)",
    alignItems: "center",
  },
  statIconWrap: {
    width: 50,
    height: 50,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    borderWidth: 1,
  },
  statValue: {
    fontSize: 25,
    fontWeight: "900",
    color: C.text,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: C.sub,
    textAlign: "center",
  },
  section: {
    marginBottom: 26,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: C.text,
    marginBottom: 12,
  },
  actionsList: {
    gap: 13,
  },
  actionCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(15,23,42,0.76)",
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    gap: 15,
  },
  actionIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
  },
  actionTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: C.text,
    marginBottom: 4,
  },
  actionSubtitle: {
    fontSize: 13,
    color: C.sub,
    lineHeight: 18,
  },
  toolsList: {
    gap: 12,
  },
  toolRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(15,23,42,0.76)",
    borderRadius: 20,
    padding: 15,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    gap: 14,
  },
  toolIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: "rgba(124,140,255,0.15)",
    borderWidth: 1,
    borderColor: "rgba(124,140,255,0.35)",
    justifyContent: "center",
    alignItems: "center",
  },
  toolTitle: {
    fontSize: 17,
    fontWeight: "900",
    color: C.text,
    marginBottom: 2,
  },
  toolDesc: {
    fontSize: 12,
    color: C.sub,
  },
  footer: {
    textAlign: "center",
    color: C.sub,
    fontSize: 12,
    marginTop: 20,
  },
});


