// apps/mobile/styles/homeStyles.js
import { StyleSheet } from "react-native";
import { C } from "./theme";

/** Icon tints for grouped tool sections (visual separation). */
export const HOME_SECTION_ICON = {
  safety: "#60A5FA",
  community: "#A78BFA",
  garages: "#38BDF8",
  account: "#A8B2F5",
};

export const homeStyles = StyleSheet.create({
  bg: { flex: 1 },
  header: {
    paddingHorizontal: 22,
    paddingTop: 10,
    paddingBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  appIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    flex: 1,
    marginRight: 14,
  },
  logoCircle: {
    width: 48,
    height: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.45)",
    backgroundColor: "rgba(99,102,241,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  appTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  appTitle: {
    color: C.text,
    fontSize: 23,
    fontWeight: "900",
    letterSpacing: 0.25,
  },
  appSubtitle: {
    color: C.sub,
    fontSize: 13,
    marginTop: 2,
    lineHeight: 17,
    opacity: 0.95,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    flexShrink: 0,
  },
  langChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.22)",
    backgroundColor: "rgba(2,6,23,0.42)",
    gap: 6,
    maxWidth: 136,
  },
  langChipText: {
    color: C.text,
    fontSize: 13,
    fontWeight: "700",
    flexShrink: 1,
  },
  profileBtn: {
    width: 44,
    height: 44,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.28)",
    backgroundColor: "rgba(15,23,42,0.72)",
  },
  logoutBtn: {
    backgroundColor: "rgba(249,115,115,0.12)",
    borderColor: "rgba(249,115,115,0.34)",
  },
  content: {
    paddingHorizontal: 22,
    paddingTop: 10,
    paddingBottom: 116,
  },
  heroPanel: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    padding: 18,
    marginBottom: 26,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  heroGlow: {
    position: "absolute",
    top: -90,
    right: -70,
    width: 210,
    height: 210,
    borderRadius: 210,
    backgroundColor: "rgba(129,140,248,0.2)",
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  heroGreeting: {
    flex: 1,
    minWidth: 0,
  },
  heroStatusRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 16,
  },
  heroSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginTop: 20,
    marginBottom: 12,
  },
  connectionChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: "rgba(34,197,94,0.09)",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.22)",
    flexShrink: 1,
  },
  overviewMetricsGrid: {
    flexDirection: "row",
    gap: 10,
  },
  metricSlot: {
    flex: 1,
    minWidth: 0,
  },
  greetingBlock: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 21,
    gap: 10,
  },
  greetingLabel: {
    color: C.sub,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "700",
    opacity: 0.95,
  },
  greetingName: {
    color: C.text,
    fontSize: 31,
    fontWeight: "900",
    marginTop: 4,
    letterSpacing: 0.15,
  },
  greetingPills: {
    alignItems: "flex-end",
    gap: 6,
    flexShrink: 0,
  },
  infoPill: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 8,
    backgroundColor: "rgba(2,6,23,0.34)",
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.16)",
  },
  infoPillLabel: {
    fontSize: 10,
    fontWeight: "800",
  },
  infoPillValue: {
    fontSize: 11,
    color: C.text,
    fontWeight: "600",
  },
  sectionPanel: {
    borderRadius: 15,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.panel,
    padding: 15,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    color: C.text,
    fontSize: 18,
    fontWeight: "900",
  },
  sectionHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: C.green,
  },
  sectionStatusText: {
    color: C.text,
    fontSize: 11,
    fontWeight: "800",
    opacity: 0.9,
  },
  overviewRow: {
    flexDirection: "row",
    gap: 13,
    marginTop: 4,
  },
  metric: {
    minHeight: 104,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.16)",
    padding: 14,
    backgroundColor: "rgba(2,6,23,0.34)",
  },
  metricLabel: {
    color: C.sub,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  metricValue: {
    color: C.text,
    fontSize: 23,
    fontWeight: "800",
    marginTop: 6,
  },
  metricHint: {
    color: C.sub,
    fontSize: 12,
    marginTop: 7,
    lineHeight: 16,
    opacity: 0.92,
  },
  overviewCard: {
    marginTop: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.22)",
    backgroundColor: "rgba(15,23,42,0.72)",
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  overviewCardCopy: {
    flex: 1,
    minWidth: 0,
  },
  overviewCardTitle: {
    color: C.text,
    fontSize: 17,
    fontWeight: "900",
  },
  overviewCardText: {
    color: C.sub,
    fontSize: 13,
    lineHeight: 17,
    marginTop: 5,
    opacity: 0.95,
  },
  overviewButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "center",
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: C.primary,
  },
  overviewButtonText: {
    color: "#fff",
    fontWeight: "900",
    fontSize: 13,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: C.divider,
    marginVertical: 21,
    opacity: 0.55,
  },
  block: { marginBottom: 26 },
  blockHeader: { marginBottom: 12 },
  blockHeaderRow: {
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
  },
  blockTitle: {
    color: C.text,
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 0.12,
  },
  blockSubtitle: {
    color: C.sub,
    fontSize: 15,
    marginTop: 5,
    lineHeight: 21,
    opacity: 0.96,
  },
  viewAllLink: {
    color: C.primary,
    fontSize: 13,
    fontWeight: "900",
    marginTop: 2,
  },
  productsPreviewRow: {
    gap: 11,
    paddingRight: 20,
    paddingVertical: 2,
  },
  productPreviewCard: {
    width: 196,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.panel,
    padding: 11,
  },
  productPreviewImage: {
    width: "100%",
    height: 102,
    borderRadius: 11,
    marginBottom: 8,
    backgroundColor: "rgba(148,163,184,0.1)",
  },
  productPreviewBadges: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginBottom: 6,
    minHeight: 18,
  },
  productFeaturedBadge: {
    borderWidth: 1,
    borderColor: "rgba(245,158,11,0.4)",
    backgroundColor: "rgba(245,158,11,0.14)",
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  productFeaturedBadgeText: {
    color: C.amber,
    fontSize: 9,
    fontWeight: "800",
  },
  productSaleBadge: {
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.35)",
    backgroundColor: "rgba(34,197,94,0.12)",
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  productSaleBadgeText: {
    color: C.green,
    fontSize: 9,
    fontWeight: "800",
  },
  productPreviewTitle: {
    color: C.text,
    fontSize: 13,
    fontWeight: "900",
    marginBottom: 4,
  },
  productPreviewPriceRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 6,
  },
  productPreviewPrice: {
    color: C.primary,
    fontSize: 14,
    fontWeight: "900",
  },
  productPreviewComparePrice: {
    color: C.sub,
    fontSize: 12,
    textDecorationLine: "line-through",
  },
  primaryGrid: {
    gap: 10,
  },
  primaryCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(15,23,42,0.72)",
    paddingVertical: 13,
    paddingHorizontal: 15,
    minHeight: 68,
  },
  primaryIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    backgroundColor: "rgba(2,6,23,0.38)",
  },
  primaryTitle: {
    color: C.text,
    fontSize: 17,
    fontWeight: "900",
  },
  primarySubtitle: {
    color: C.sub,
    fontSize: 13,
    marginTop: 3,
    lineHeight: 17,
    opacity: 0.96,
  },
  toolSection: {
    marginBottom: 18,
  },
  toolSectionLabel: {
    color: C.sub,
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1.05,
    textTransform: "uppercase",
    marginBottom: 8,
    opacity: 0.85,
  },
  toolSectionCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.26)",
    backgroundColor: "rgba(15,23,42,0.7)",
    overflow: "hidden",
  },
  secondaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 15,
    paddingVertical: 15,
    minHeight: 72,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(148,163,184,0.2)",
  },
  secondaryRowLast: {
    borderBottomWidth: 0,
  },
  secondaryIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(99,102,241,0.08)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
  },
  secondaryTitle: {
    color: C.text,
    fontSize: 17,
    fontWeight: "900",
  },
  secondaryDesc: {
    color: C.sub,
    fontSize: 13,
    marginTop: 3,
    lineHeight: 17,
    opacity: 0.95,
  },
  tipsPanel: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.26)",
    backgroundColor: "rgba(15,23,42,0.72)",
    padding: 17,
    gap: 13,
  },
  tipLineRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  tipBullet: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: C.primary,
    marginTop: 5,
  },
  tipText: {
    color: C.sub,
    fontSize: 14,
    lineHeight: 19,
    flex: 1,
    opacity: 0.96,
  },
  footer: {
    color: C.sub,
    fontSize: 13,
    textAlign: "center",
    marginTop: 14,
    paddingHorizontal: 12,
    lineHeight: 16,
    opacity: 0.85,
  },
});
