// apps/mobile/styles/homeStyles.js
import { StyleSheet } from "react-native";
import { C } from "./theme";

/** Icon tints for grouped tool sections (visual separation). */
export const HOME_SECTION_ICON = {
  safety: "#60A5FA",
  community: "#A78BFA",
  garages: "#38BDF8",
  account: "#A8B2F5",
};

export const homeStyles = StyleSheet.create({
  bg: { flex: 1 },
  header: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  appIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    marginRight: 6,
  },
  logoCircle: {
    width: 44,
    height: 44,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(15,23,42,0.92)",
    alignItems: "center",
    justifyContent: "center",
  },
  appTitle: {
    color: C.text,
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 0.25,
  },
  appSubtitle: {
    color: C.sub,
    fontSize: 13,
    marginTop: 2,
    lineHeight: 17,
    opacity: 0.95,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  langChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(15,23,42,0.88)",
    gap: 5,
    maxWidth: 128,
  },
  langChipText: {
    color: C.text,
    fontSize: 13,
    fontWeight: "700",
    flexShrink: 1,
  },
  profileBtn: {
    width: 45,
    height: 45,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(15,23,42,0.92)",
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 6,
    paddingBottom: 106,
  },
  greetingBlock: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 21,
    gap: 10,
  },
  greetingLabel: {
    color: C.sub,
    fontSize: 14,
    lineHeight: 18,
  },
  greetingName: {
    color: C.text,
    fontSize: 24,
    fontWeight: "900",
    marginTop: 4,
    letterSpacing: 0.15,
  },
  greetingPills: {
    alignItems: "flex-end",
    gap: 6,
    flexShrink: 0,
  },
  infoPill: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "rgba(15,23,42,0.9)",
    borderWidth: 1,
    borderColor: C.border,
  },
  infoPillLabel: {
    fontSize: 10,
    fontWeight: "800",
  },
  infoPillValue: {
    fontSize: 11,
    color: C.text,
    fontWeight: "600",
  },
  sectionPanel: {
    borderRadius: 15,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.panel,
    padding: 15,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    color: C.text,
    fontSize: 17,
    fontWeight: "900",
  },
  sectionHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: C.green,
  },
  sectionStatusText: {
    color: C.sub,
    fontSize: 12,
    fontWeight: "600",
  },
  overviewRow: {
    flexDirection: "row",
    gap: 13,
    marginTop: 4,
  },
  metric: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    padding: 13,
    backgroundColor: C.panelSoft,
    marginBottom: 11,
  },
  metricLabel: {
    color: C.sub,
    fontSize: 13,
    lineHeight: 16,
  },
  metricValue: {
    color: C.text,
    fontSize: 18,
    fontWeight: "800",
    marginTop: 4,
  },
  metricHint: {
    color: C.sub,
    fontSize: 12,
    marginTop: 5,
    lineHeight: 16,
    opacity: 0.92,
  },
  overviewCard: {
    width: 156,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(15,23,42,0.96)",
    padding: 13,
    justifyContent: "space-between",
  },
  overviewCardTitle: {
    color: C.text,
    fontSize: 15,
    fontWeight: "900",
  },
  overviewCardText: {
    color: C.sub,
    fontSize: 13,
    lineHeight: 17,
    marginTop: 4,
    marginBottom: 9,
    opacity: 0.95,
  },
  overviewButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: C.primary,
  },
  overviewButtonText: {
    color: "#fff",
    fontWeight: "900",
    fontSize: 12,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: C.divider,
    marginVertical: 21,
    opacity: 0.55,
  },
  block: { marginBottom: 22 },
  blockHeader: { marginBottom: 12 },
  blockHeaderRow: {
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
  },
  blockTitle: {
    color: C.text,
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.12,
  },
  blockSubtitle: {
    color: C.sub,
    fontSize: 15,
    marginTop: 5,
    lineHeight: 21,
    opacity: 0.96,
  },
  viewAllLink: {
    color: C.primary,
    fontSize: 13,
    fontWeight: "900",
    marginTop: 2,
  },
  productsPreviewRow: {
    gap: 11,
    paddingRight: 20,
    paddingVertical: 2,
  },
  productPreviewCard: {
    width: 196,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.panel,
    padding: 11,
  },
  productPreviewImage: {
    width: "100%",
    height: 102,
    borderRadius: 11,
    marginBottom: 8,
    backgroundColor: "rgba(148,163,184,0.1)",
  },
  productPreviewBadges: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginBottom: 6,
    minHeight: 18,
  },
  productFeaturedBadge: {
    borderWidth: 1,
    borderColor: "rgba(245,158,11,0.4)",
    backgroundColor: "rgba(245,158,11,0.14)",
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  productFeaturedBadgeText: {
    color: C.amber,
    fontSize: 9,
    fontWeight: "800",
  },
  productSaleBadge: {
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.35)",
    backgroundColor: "rgba(34,197,94,0.12)",
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  productSaleBadgeText: {
    color: C.green,
    fontSize: 9,
    fontWeight: "800",
  },
  productPreviewTitle: {
    color: C.text,
    fontSize: 13,
    fontWeight: "900",
    marginBottom: 4,
  },
  productPreviewPriceRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 6,
  },
  productPreviewPrice: {
    color: C.primary,
    fontSize: 14,
    fontWeight: "900",
  },
  productPreviewComparePrice: {
    color: C.sub,
    fontSize: 12,
    textDecorationLine: "line-through",
  },
  primaryGrid: {
    gap: 12,
  },
  primaryCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.panel,
    paddingVertical: 14,
    paddingHorizontal: 14,
    minHeight: 66,
  },
  primaryIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    backgroundColor: "rgba(15,23,42,0.95)",
  },
  primaryTitle: {
    color: C.text,
    fontSize: 17,
    fontWeight: "900",
  },
  primarySubtitle: {
    color: C.sub,
    fontSize: 14,
    marginTop: 3,
    lineHeight: 19,
    opacity: 0.96,
  },
  toolSection: {
    marginBottom: 16,
  },
  toolSectionLabel: {
    color: C.sub,
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1.05,
    textTransform: "uppercase",
    marginBottom: 8,
    opacity: 0.85,
  },
  toolSectionCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.panel,
    overflow: "hidden",
  },
  secondaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    paddingHorizontal: 14,
    paddingVertical: 13,
    minHeight: 64,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(148,163,184,0.2)",
  },
  secondaryRowLast: {
    borderBottomWidth: 0,
  },
  secondaryIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(99,102,241,0.08)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
  },
  secondaryTitle: {
    color: C.text,
    fontSize: 16,
    fontWeight: "900",
  },
  secondaryDesc: {
    color: C.sub,
    fontSize: 13,
    marginTop: 3,
    lineHeight: 17,
    opacity: 0.95,
  },
  tipsPanel: {
    borderRadius: 15,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.panel,
    padding: 15,
    gap: 12,
  },
  tipLineRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  tipBullet: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: C.primary,
    marginTop: 5,
  },
  tipText: {
    color: C.sub,
    fontSize: 14,
    lineHeight: 19,
    flex: 1,
    opacity: 0.96,
  },
  footer: {
    color: C.sub,
    fontSize: 13,
    textAlign: "center",
    marginTop: 14,
    paddingHorizontal: 12,
    lineHeight: 16,
    opacity: 0.85,
  },
});
