import { StyleSheet, Dimensions, Platform } from "react-native";
import { C } from "./theme";

const { width: W } = Dimensions.get("window");

export const MAP_HEIGHT = Math.min(380, Math.round(W * 0.92));

export const mapForGaragesStyles = StyleSheet.create({
  headerOuter: {
    paddingHorizontal: 18,
    paddingBottom: 14,
    backgroundColor: "rgba(2,6,23,0.72)",
    overflow: "hidden",
  },
  headerGradientBg: {
    ...StyleSheet.absoluteFillObject,
    height: 72,
    opacity: 0.9,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  backBtn: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.72)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
  },
  headerTitleWrap: {
    flex: 1,
    paddingTop: 2,
  },
  headerEyebrow: {
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 2.2,
    color: C.primary,
    marginBottom: 4,
    opacity: 0.95,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: C.text,
    letterSpacing: -0.3,
    lineHeight: 28,
  },
  headerSubtitle: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 18,
    color: C.sub,
    fontWeight: "500",
  },

  scrollBody: {
    flexGrow: 1,
    paddingBottom: Platform.OS === "ios" ? 32 : 20,
  },

  filtersSection: {
    marginTop: 4,
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  filtersLabel: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.2,
    color: C.sub,
    marginBottom: 8,
    opacity: 0.85,
  },

  searchOuter: {
    marginHorizontal: 16,
    marginBottom: 4,
    borderRadius: 20,
    padding: 1.5,
    overflow: "hidden",
  },
  searchInner: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === "ios" ? 12 : 10,
    borderRadius: 19,
    backgroundColor: "rgba(15,23,42,0.78)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.18)",
  },
  searchIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(99,102,241,0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: C.text,
    fontWeight: "500",
  },

  chipScroll: {
    marginBottom: 4,
    paddingLeft: 16,
    maxHeight: 44,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    marginRight: 8,
    backgroundColor: "rgba(15,23,42,0.72)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.2)",
  },
  chipActive: {
    borderColor: "rgba(99,102,241,0.65)",
    backgroundColor: "rgba(99,102,241,0.18)",
    shadowColor: C.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 4,
  },
  chipDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "transparent",
    marginRight: 8,
  },
  chipDotActive: {
    backgroundColor: C.green,
  },
  chipText: {
    fontSize: 13,
    fontWeight: "700",
    color: C.sub,
    letterSpacing: 0.2,
  },
  chipTextActive: {
    color: C.text,
  },

  mapGradientBorder: {
    marginHorizontal: 16,
    borderRadius: 26,
    padding: 2,
    marginBottom: 4,
  },
  mapInner: {
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "#0f172a",
  },
  mapWrap: {
    height: MAP_HEIGHT,
    width: "100%",
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  mapOverlayLayer: {
    ...StyleSheet.absoluteFillObject,
    pointerEvents: "box-none",
    zIndex: 24,
    elevation: 24,
  },
  mapBadge: {
    position: "absolute",
    bottom: 14,
    left: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 14,
    backgroundColor: "rgba(2,6,23,0.88)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.35)",
  },
  mapBadgeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: C.green,
  },
  mapBadgeText: {
    color: C.text,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.2,
  },

  /** Floating control — center map on current GPS position */
  mapRecenterBtn: {
    position: "absolute",
    bottom: 14,
    right: 14,
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.96)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.45)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    zIndex: 26,
    elevation: 26,
  },
  mapRecenterBtnFullscreen: {
    bottom: 18,
    right: 16,
  },

  /** Expand map to fullscreen modal */
  mapExpandBtn: {
    position: "absolute",
    top: 14,
    right: 14,
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.96)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.45)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 26,
    zIndex: 26,
  },

  mapGradientBorderFullscreen: {
    marginHorizontal: 0,
    marginBottom: 0,
    borderRadius: 0,
    flex: 1,
    padding: 0,
  },
  mapInnerFullscreen: {
    borderRadius: 0,
    flex: 1,
  },
  mapWrapFullscreen: {
    flex: 1,
    width: "100%",
    minHeight: 200,
  },

  mapFullscreenRoot: {
    flex: 1,
    backgroundColor: "#020617",
  },
  mapFullscreenToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(99,102,241,0.15)",
    backgroundColor: "rgba(2,6,23,0.98)",
  },
  mapFullscreenTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "800",
    color: C.text,
    letterSpacing: -0.2,
  },
  mapFullscreenCloseBtn: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.95)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
  },
  mapFullscreenMapShell: {
    flex: 1,
    minHeight: 0,
  },

  webFallback: {
    minHeight: MAP_HEIGHT,
    marginHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.25)",
    alignItems: "center",
    justifyContent: "center",
    padding: 28,
    backgroundColor: "rgba(15,23,42,0.92)",
  },
  webFallbackText: {
    color: C.sub,
    textAlign: "center",
    marginTop: 14,
    lineHeight: 21,
    fontSize: 14,
    fontWeight: "500",
  },

  centerBlock: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 28,
  },
  loadingPulseRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: "rgba(99,102,241,0.35)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  stateTitle: {
    fontSize: 19,
    fontWeight: "800",
    color: C.text,
    marginTop: 14,
    textAlign: "center",
    letterSpacing: -0.2,
  },
  stateBody: {
    fontSize: 14,
    color: C.sub,
    marginTop: 10,
    textAlign: "center",
    lineHeight: 21,
    fontWeight: "500",
    maxWidth: 300,
  },
  primaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 22,
    paddingVertical: 15,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignSelf: "stretch",
    maxWidth: 320,
    overflow: "hidden",
  },
  primaryBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 0.3,
  },

  detailCard: {
    marginHorizontal: 16,
    marginTop: 14,
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.22)",
    backgroundColor: "rgba(15,23,42,0.96)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 12,
  },
  detailCardTopAccent: {
    height: 3,
    width: "100%",
  },
  detailCardBody: {
    padding: 18,
    paddingTop: 16,
  },
  detailHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 4,
  },
  detailTitle: {
    flex: 1,
    fontSize: 19,
    fontWeight: "800",
    color: C.text,
    letterSpacing: -0.2,
    lineHeight: 24,
  },
  distancePill: {
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: "rgba(34,197,94,0.12)",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.35)",
  },
  distancePillText: {
    color: C.green,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.3,
  },

  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    gap: 8,
  },
  ratingBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: "rgba(250,204,21,0.1)",
    borderWidth: 1,
    borderColor: "rgba(250,204,21,0.22)",
  },
  ratingText: {
    color: C.amber,
    fontWeight: "800",
    fontSize: 14,
  },
  ratingMuted: {
    marginTop: 8,
    fontSize: 13,
    color: C.sub,
    fontWeight: "500",
    fontStyle: "italic",
  },

  detailDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(148,163,184,0.18)",
    marginVertical: 14,
  },

  detailRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
    gap: 12,
  },
  detailIconCircle: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "rgba(99,102,241,0.1)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  detailRowText: {
    flex: 1,
  },
  detailLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: C.sub,
    letterSpacing: 0.6,
    marginBottom: 3,
    textTransform: "uppercase",
  },
  detailValue: {
    fontSize: 14,
    color: C.text,
    lineHeight: 20,
    fontWeight: "500",
  },

  servicesWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 2,
  },
  serviceTag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: "rgba(59,130,246,0.1)",
    borderWidth: 1,
    borderColor: "rgba(59,130,246,0.28)",
  },
  serviceTagText: {
    fontSize: 12,
    color: C.blue,
    fontWeight: "700",
  },

  actionsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 18,
  },
  actionBtnGhost: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: "rgba(15,23,42,0.95)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.28)",
  },
  actionBtnGhostText: {
    color: C.text,
    fontWeight: "800",
    fontSize: 14,
    letterSpacing: 0.2,
  },
  actionBtnGradientOuter: {
    flex: 1,
    borderRadius: 16,
    overflow: "hidden",
  },
  actionBtnGradientInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
  },
  actionBtnGradientText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 14,
    letterSpacing: 0.25,
  },

  emptyCard: {
    marginHorizontal: 16,
    marginTop: 14,
    padding: 24,
    borderRadius: 20,
    alignItems: "center",
    backgroundColor: "rgba(15,23,42,0.75)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.15)",
    borderStyle: "dashed",
  },
  emptyIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: "rgba(99,102,241,0.08)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
});
