// apps/mobile/styles/marketplaceStyles.js
import { StyleSheet } from "react-native";
import { C } from "./theme";

export const marketplaceStyles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  backBtn: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "rgba(15,23,42,0.72)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 20,
    fontWeight: "900",
    color: C.text,
    marginRight: 40,
  },
  formHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 22,
    paddingTop: 10,
    paddingBottom: 12,
    gap: 12,
  },
  formHeaderTitle: {
    flex: 1,
    textAlign: "center",
    color: C.text,
    fontSize: 22,
    fontWeight: "900",
  },
  formHeaderSpacer: {
    width: 46,
  },
  body: {
    flex: 1,
    paddingHorizontal: 22,
    paddingTop: 10,
  },
  garageListingsHero: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    padding: 18,
    marginBottom: 26,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  garageListingsHeroGlow: {
    position: "absolute",
    top: -90,
    right: -70,
    width: 210,
    height: 210,
    borderRadius: 210,
    backgroundColor: "rgba(129,140,248,0.2)",
  },
  garageListingsHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 13,
  },
  garageListingsHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  garageListingsEyebrow: {
    color: "#C7D2FE",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.3,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  garageListingsTitle: {
    color: C.text,
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: -0.3,
  },
  garageListingsSubtitle: {
    color: C.sub,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
  },
  garageListingsAddBtn: {
    marginTop: 18,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: C.primary,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 999,
  },
  garageListingsAddText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "900",
  },
  subtitle: {
    color: C.sub,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  sectionTitle: {
    color: C.text,
    fontSize: 20,
    fontWeight: "900",
  },
  sectionWrap: {
    marginBottom: 14,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  sectionSubtitle: {
    color: C.sub,
    fontSize: 13,
    marginBottom: 10,
  },
  featuredRow: {
    paddingRight: 20,
    gap: 12,
  },
  storefrontRow: {
    paddingRight: 20,
    gap: 12,
  },
  storefrontCardWrap: {
    width: 280,
  },
  featuredCard: {
    width: 260,
    backgroundColor: "rgba(15,23,42,0.82)",
    borderRadius: 22,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.22)",
  },
  featuredThumb: {
    width: "100%",
    height: 148,
    borderRadius: 16,
    marginBottom: 10,
    backgroundColor: "rgba(148,163,184,0.12)",
  },
  searchInput: {
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: C.text,
    fontSize: 16,
    marginBottom: 16,
    backgroundColor: "rgba(15,23,42,0.5)",
  },
  card: {
    backgroundColor: "rgba(15,23,42,0.78)",
    borderRadius: 24,
    padding: 17,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
  },
  garageHeroCard: {
    backgroundColor: "rgba(15,23,42,0.85)",
    borderRadius: 24,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.28)",
  },
  garageHeroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
  },
  garageHeroIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.35)",
    backgroundColor: "rgba(99,102,241,0.12)",
    justifyContent: "center",
    alignItems: "center",
  },
  garageHeroDescription: {
    color: C.text,
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 6,
  },
  garageHeroMissing: {
    color: C.sub,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 8,
    fontStyle: "italic",
  },
  cardTitle: {
    color: C.text,
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 6,
  },
  cardMeta: {
    color: C.sub,
    fontSize: 14,
    marginBottom: 8,
  },
  imageWrap: {
    position: "relative",
    marginBottom: 10,
  },
  imageOverlayBadges: {
    position: "absolute",
    top: 8,
    left: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  badgeRowWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  featuredBadge: {
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.42)",
    backgroundColor: "rgba(99,102,241,0.14)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  featuredBadgeText: {
    color: "#C7D2FE",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  saleBadge: {
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.35)",
    backgroundColor: "rgba(34,197,94,0.12)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  saleBadgeText: {
    color: C.green,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 8,
    marginBottom: 4,
  },
  priceText: {
    color: C.primary,
    fontSize: 17,
    fontWeight: "800",
  },
  priceCompareText: {
    color: "rgba(148,163,184,0.9)",
    fontSize: 14,
    textDecorationLine: "line-through",
  },
  thumb: {
    width: "100%",
    height: 160,
    borderRadius: 18,
    marginBottom: 10,
    backgroundColor: "rgba(148,163,184,0.12)",
  },
  detailImage: {
    width: "100%",
    height: 220,
    borderRadius: 16,
    marginBottom: 16,
    backgroundColor: "rgba(148,163,184,0.12)",
  },
  detailTitle: {
    color: C.text,
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 8,
  },
  detailSeller: {
    color: C.sub,
    fontSize: 15,
    marginBottom: 12,
  },
  detailDesc: {
    color: C.text,
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 20,
  },
  primaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: C.primary,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 18,
    marginBottom: 10,
  },
  primaryBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  secondaryBtn: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.35)",
    marginBottom: 8,
  },
  secondaryBtnText: {
    color: C.text,
    fontWeight: "600",
    fontSize: 15,
  },
  fabRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginBottom: 12,
  },
  fab: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: C.amber,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  fabText: {
    color: "#0f172a",
    fontWeight: "700",
    fontSize: 14,
  },
  label: {
    color: C.sub,
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 6,
    marginTop: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: C.text,
    fontSize: 16,
    backgroundColor: "rgba(2,6,23,0.34)",
  },
  inputMultiline: {
    minHeight: 100,
    textAlignVertical: "top",
  },
  badgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  inactiveBadge: {
    backgroundColor: "rgba(249,115,115,0.2)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  inactiveBadgeText: {
    color: C.red,
    fontSize: 12,
    fontWeight: "700",
  },
  rowActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  smallBtn: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.3)",
  },
  smallBtnContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  dangerBtn: {
    borderColor: "rgba(249,115,115,0.45)",
    backgroundColor: "rgba(249,115,115,0.08)",
  },
  smallBtnText: {
    color: C.text,
    fontWeight: "600",
    fontSize: 14,
  },
  dangerBtnText: {
    color: C.red,
    fontWeight: "700",
    fontSize: 14,
  },
  imagePickerBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.35)",
    backgroundColor: "rgba(99,102,241,0.12)",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  imagePickerText: {
    color: C.primary,
    fontWeight: "800",
    fontSize: 15,
  },
  previewThumb: {
    width: 96,
    height: 96,
    borderRadius: 18,
    backgroundColor: "rgba(148,163,184,0.12)",
  },
  formContent: {
    paddingBottom: 42,
  },
  formCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.16)",
    backgroundColor: "rgba(15,23,42,0.72)",
    padding: 16,
    marginBottom: 14,
  },
  formSectionTitle: {
    color: C.text,
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 4,
  },
  priceGrid: {
    flexDirection: "row",
    gap: 10,
  },
  priceField: {
    flex: 1,
    minWidth: 0,
  },
  fieldHint: {
    color: C.sub,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 8,
    opacity: 0.9,
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(148,163,184,0.12)",
  },
  switchCopy: {
    flex: 1,
    minWidth: 0,
  },
  switchTitle: {
    color: C.text,
    fontSize: 15,
    fontWeight: "800",
  },
  switchHint: {
    color: C.sub,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  photoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginTop: 12,
  },
  previewThumbPlaceholder: {
    width: 96,
    height: 96,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "rgba(129,140,248,0.35)",
    backgroundColor: "rgba(99,102,241,0.08)",
  },
  photoActions: {
    flex: 1,
    gap: 10,
    alignItems: "flex-start",
  },
  removePhotoBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  removePhotoText: {
    color: C.red,
    fontSize: 13,
    fontWeight: "800",
  },
  formActions: {
    gap: 12,
    marginTop: 4,
  },
});
