// apps/mobile/styles/nearestGaragesStyles.js
import { StyleSheet } from "react-native";
import { C } from "./theme";

export const nearestGaragesStyles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(148,163,184,0.15)",
  },
  backBtn: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 18,
    fontWeight: "800",
    color: C.text,
    marginRight: 40,
  },
  body: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  subtitle: {
    color: C.sub,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  openMapBanner: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    marginBottom: 16,
    borderRadius: 14,
    backgroundColor: "rgba(99,102,241,0.1)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.28)",
  },
  openMapBannerTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: C.text,
  },
  openMapBannerDesc: {
    fontSize: 12,
    color: C.sub,
    marginTop: 2,
    lineHeight: 16,
  },
  primaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: C.primary,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    marginBottom: 12,
  },
  primaryBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  secondaryBtn: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.35)",
    marginBottom: 8,
  },
  secondaryBtnText: {
    color: C.text,
    fontWeight: "600",
    fontSize: 15,
  },
  centerBlock: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 24,
    paddingHorizontal: 12,
  },
  stateTitle: {
    color: C.text,
    fontSize: 18,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 12,
  },
  stateBody: {
    color: C.sub,
    fontSize: 14,
    textAlign: "center",
    marginTop: 8,
    lineHeight: 20,
    maxWidth: 320,
  },
  listHeading: {
    color: C.sub,
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 10,
    marginTop: 8,
  },
  card: {
    backgroundColor: "rgba(15,23,42,0.95)",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.15)",
  },
  cardTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  cardTitle: {
    flex: 1,
    minWidth: 0,
    color: C.text,
    fontSize: 17,
    fontWeight: "800",
    lineHeight: 22,
  },
  distancePill: {
    flexShrink: 0,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "rgba(99,102,241,0.18)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.4)",
  },
  distancePillText: {
    color: C.primary,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  cardDescription: {
    color: C.sub,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    marginTop: 2,
    marginBottom: 8,
  },
  cardHoursRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 6,
    marginTop: 4,
  },
  cardHoursIcon: {
    marginTop: 1,
    opacity: 0.85,
  },
  cardHoursText: {
    flex: 1,
    minWidth: 0,
    color: C.sub,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    opacity: 0.9,
  },
  cardAddress: {
    color: C.sub,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 4,
  },
  cardAddressBlock: {
    marginBottom: 4,
  },
  cardAddressMuted: {
    color: C.sub,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
  },
  cardAddressHint: {
    color: C.sub,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
    opacity: 0.9,
  },
  cardListingMissing: {
    fontSize: 12,
    lineHeight: 17,
    color: C.sub,
    opacity: 0.75,
    fontStyle: "italic",
    marginTop: 6,
    marginBottom: 4,
  },
  cardEmailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  cardEmailText: {
    flex: 1,
    minWidth: 0,
    color: C.sub,
    fontSize: 13,
  },
  cardActionsRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 8,
    marginTop: 14,
  },
  cardActionBtn: {
    flex: 1,
    minWidth: 0,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderRadius: 12,
    backgroundColor: "rgba(99,102,241,0.2)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.45)",
  },
  cardActionBtnSecondary: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderColor: "rgba(148,163,184,0.35)",
  },
  cardActionBtnText: {
    color: C.primary,
    fontWeight: "700",
    fontSize: 12,
    textAlign: "center",
    lineHeight: 15,
  },
  cardActionBtnTextSecondary: {
    color: C.text,
  },
  listContent: {
    paddingBottom: 40,
  },
  listContentGrow: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  emptyInList: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 48,
    paddingHorizontal: 16,
    minHeight: 280,
  },
});
