// apps/mobile/styles/profileStyles.js
import { StyleSheet } from "react-native";
import { C } from "./theme";

export const profileStyles = StyleSheet.create({
  bg: { flex: 1 },
  header: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(15,23,42,0.95)",
  },
  headerTitle: {
    color: C.text,
    fontSize: 20,
    fontWeight: "900",
  },
  refreshBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(15,23,42,0.95)",
  },
  settingsBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(15,23,42,0.95)",
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 32,
  },
  profileCard: {
    backgroundColor: C.panel,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: C.border,
    padding: 24,
    alignItems: "center",
    marginBottom: 16,
  },
  avatarContainer: {
    position: "relative",
    marginBottom: 12,
  },
  avatarGradient: {
    width: 100,
    height: 100,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "rgba(255,255,255,0.2)",
  },
  avatarText: {
    color: "#fff",
    fontSize: 36,
    fontWeight: "900",
    letterSpacing: 2,
  },
  roleBadge: {
    position: "absolute",
    bottom: -4,
    right: -4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: C.bg1,
  },
  roleText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  name: {
    color: C.text,
    fontSize: 24,
    fontWeight: "900",
    marginTop: 8,
  },
  email: {
    color: C.sub,
    fontSize: 14,
    marginTop: 4,
  },
  memberSince: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(15,23,42,0.9)",
    borderWidth: 1,
    borderColor: C.border,
  },
  memberSinceText: {
    color: C.sub,
    fontSize: 12,
    fontWeight: "600",
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 20,
  },
  statCard: {
    flexBasis: "47%",
    backgroundColor: C.panel,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.border,
    padding: 14,
    alignItems: "center",
  },
  statIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    marginBottom: 8,
  },
  statValue: {
    color: C.text,
    fontSize: 24,
    fontWeight: "900",
    marginBottom: 4,
  },
  statLabel: {
    color: C.sub,
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    color: C.sub,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.4,
    marginBottom: 10,
    marginLeft: 4,
  },
  actionsCard: {
    backgroundColor: C.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.border,
    overflow: "hidden",
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(15,23,42,0.9)",
  },
  actionLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 12,
  },
  actionIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: C.primarySoft,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: C.border,
  },
  actionTitle: {
    color: C.text,
    fontSize: 15,
    fontWeight: "700",
  },
  actionSubtitle: {
    color: C.sub,
    fontSize: 12,
    marginTop: 2,
  },
  infoCard: {
    backgroundColor: C.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.border,
    padding: 14,
    gap: 12,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  infoLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  infoLabel: {
    color: C.sub,
    fontSize: 13,
  },
  infoValue: {
    color: C.text,
    fontSize: 13,
    fontWeight: "600",
  },
  preferencesCard: {
    backgroundColor: C.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.border,
    overflow: "hidden",
  },
  preferenceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(15,23,42,0.9)",
  },
  preferenceLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  preferenceTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: "600",
  },
  preferenceRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  preferenceValue: {
    color: C.sub,
    fontSize: 13,
  },
  logoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: "rgba(249,115,115,0.12)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(249,115,115,0.35)",
    paddingVertical: 14,
    marginTop: 8,
    marginBottom: 20,
  },
  logoutText: {
    color: C.red,
    fontSize: 16,
    fontWeight: "800",
  },
  footer: {
    color: C.sub,
    fontSize: 11,
    textAlign: "center",
    marginTop: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.65)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  modalCard: {
    width: "100%",
    backgroundColor: "rgba(15,23,42,0.97)",
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  modalTitle: {
    color: C.text,
    fontSize: 20,
    fontWeight: "900",
  },
  modalSubtitle: {
    color: C.sub,
    fontSize: 13,
    marginTop: 6,
    marginBottom: 14,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.03)",
    color: C.text,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
    marginTop: 16,
  },
  modalButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: C.primary,
  },
  modalButtonText: {
    color: "#fff",
    fontWeight: "800",
  },
  modalButtonGhost: {
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  modalButtonGhostText: {
    color: C.text,
    fontWeight: "700",
  },
});

