// apps/mobile/styles/profileStyles.js
import { StyleSheet } from "react-native";
import { C } from "./theme";

export const profileStyles = StyleSheet.create({
  bg: { flex: 1 },
  header: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    backgroundColor: "rgba(15,23,42,0.72)",
  },
  headerTitle: {
    color: C.text,
    fontSize: 20,
    fontWeight: "900",
  },
  refreshBtn: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    backgroundColor: "rgba(15,23,42,0.72)",
  },
  settingsBtn: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    backgroundColor: "rgba(15,23,42,0.72)",
  },
  content: {
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 32,
  },
  profileCard: {
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    padding: 24,
    alignItems: "center",
    marginBottom: 18,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  profileGlow: {
    position: "absolute",
    top: -90,
    right: -70,
    width: 210,
    height: 210,
    borderRadius: 210,
    backgroundColor: "rgba(129,140,248,0.2)",
  },
  avatarContainer: {
    position: "relative",
    marginBottom: 12,
  },
  avatarGradient: {
    width: 100,
    height: 100,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "rgba(255,255,255,0.2)",
  },
  avatarText: {
    color: "#fff",
    fontSize: 36,
    fontWeight: "900",
    letterSpacing: 2,
  },
  roleBadge: {
    position: "absolute",
    bottom: -4,
    right: -4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: C.bg1,
  },
  roleText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  name: {
    color: C.text,
    fontSize: 24,
    fontWeight: "900",
    marginTop: 8,
  },
  email: {
    color: C.sub,
    fontSize: 14,
    marginTop: 4,
  },
  phoneText: {
    color: C.sub,
    fontSize: 13,
    marginTop: 4,
  },
  memberSince: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(15,23,42,0.9)",
    borderWidth: 1,
    borderColor: C.border,
  },
  memberSinceText: {
    color: C.sub,
    fontSize: 12,
    fontWeight: "600",
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 20,
  },
  statCard: {
    flexBasis: "47%",
    backgroundColor: "rgba(15,23,42,0.76)",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    padding: 14,
    alignItems: "center",
  },
  statIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    marginBottom: 8,
  },
  statValue: {
    color: C.text,
    fontSize: 24,
    fontWeight: "900",
    marginBottom: 4,
  },
  statLabel: {
    color: C.sub,
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    color: C.sub,
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 1.1,
    textTransform: "uppercase",
    marginBottom: 10,
    marginLeft: 4,
  },
  actionsCard: {
    backgroundColor: "rgba(15,23,42,0.76)",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    overflow: "hidden",
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(15,23,42,0.9)",
  },
  actionLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 12,
  },
  actionIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: C.primarySoft,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: C.border,
  },
  actionTitle: {
    color: C.text,
    fontSize: 15,
    fontWeight: "700",
  },
  actionSubtitle: {
    color: C.sub,
    fontSize: 12,
    marginTop: 2,
  },
  infoCard: {
    backgroundColor: "rgba(15,23,42,0.76)",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    padding: 14,
    gap: 12,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  infoLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  infoLabel: {
    color: C.sub,
    fontSize: 13,
  },
  infoValue: {
    color: C.text,
    fontSize: 13,
    fontWeight: "600",
  },
  preferencesCard: {
    backgroundColor: "rgba(15,23,42,0.76)",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    overflow: "hidden",
  },
  preferenceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(15,23,42,0.9)",
  },
  preferenceLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  preferenceTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: "600",
  },
  preferenceRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  preferenceValue: {
    color: C.sub,
    fontSize: 13,
  },
  logoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: "rgba(249,115,115,0.12)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(249,115,115,0.35)",
    paddingVertical: 14,
    marginTop: 8,
    marginBottom: 20,
  },
  logoutText: {
    color: C.red,
    fontSize: 16,
    fontWeight: "800",
  },
  footer: {
    color: C.sub,
    fontSize: 11,
    textAlign: "center",
    marginTop: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 18,
  },
  modalCard: {
    width: "100%",
    backgroundColor: "#020617",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.16)",
    overflow: "hidden",
  },
  modalHero: {
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(199,210,254,0.14)",
    overflow: "hidden",
  },
  modalHeroGlow: {
    position: "absolute",
    top: -80,
    right: -60,
    width: 170,
    height: 170,
    borderRadius: 170,
    backgroundColor: "rgba(129,140,248,0.18)",
  },
  modalTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  modalIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.38)",
    backgroundColor: "rgba(99,102,241,0.14)",
  },
  modalTitle: {
    color: C.text,
    fontSize: 20,
    fontWeight: "900",
  },
  modalSubtitle: {
    color: C.sub,
    fontSize: 13,
    marginTop: 6,
    marginBottom: 0,
  },
  modalFormCard: {
    margin: 18,
    padding: 16,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.14)",
    backgroundColor: "rgba(15,23,42,0.72)",
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.16)",
    borderRadius: 18,
    backgroundColor: "rgba(2,6,23,0.34)",
    color: C.text,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  modalTextArea: {
    minHeight: 88,
    textAlignVertical: "top",
  },
  modalTextAreaShort: {
    minHeight: 72,
    textAlignVertical: "top",
  },
  modalFieldLabel: {
    color: C.sub,
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 7,
    marginTop: 12,
  },
  modalScroll: {
    maxHeight: "88%",
    width: "100%",
  },
  modalUseLocationBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  modalApplyFromLinkBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  modalCoordinatesHelp: {
    color: C.sub,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 14,
    marginBottom: 2,
  },
  modalUseLocationBtnText: {
    color: C.primary,
    fontSize: 15,
    fontWeight: "700",
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
    paddingHorizontal: 18,
    paddingBottom: 18,
    marginTop: 0,
  },
  modalButton: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: C.primary,
  },
  modalButtonText: {
    color: "#fff",
    fontWeight: "800",
  },
  modalButtonGhost: {
    backgroundColor: "rgba(15,23,42,0.74)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
  },
  modalButtonGhostText: {
    color: C.text,
    fontWeight: "700",
  },
});

