// apps/mobile/styles/vehiclesStyles.js
import { StyleSheet } from "react-native";
import { C } from "./theme";

export const vehiclesStyles = StyleSheet.create({
  heroHeader: {
    marginHorizontal: 14,
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    paddingHorizontal: 14,
    paddingVertical: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  heroGlow: {
    position: "absolute",
    top: -90,
    right: -70,
    width: 210,
    height: 210,
    borderRadius: 210,
    backgroundColor: "rgba(129,140,248,0.2)",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  backBtn: {
    width: 50,
    height: 50,
    borderRadius: 16,
    backgroundColor: "rgba(15,23,42,0.72)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.25)",
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: C.text,
    letterSpacing: -0.2,
  },
  headerTitleWrap: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  headerEyebrow: {
    color: "#C7D2FE",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.1,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  headerSpacer: {
    width: 50,
  },
  addBtn: {
    width: 50,
    height: 50,
    borderRadius: 17,
    backgroundColor: C.primary,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.35)",
    justifyContent: "center",
    alignItems: "center",
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
  },
  loadingText: {
    color: C.sub,
    marginTop: 12,
  },
  emptyText: {
    color: C.sub,
    fontSize: 16,
    marginTop: 16,
    textAlign: "center",
  },
  addFirstBtn: {
    marginTop: 24,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: C.primary,
    borderRadius: 16,
  },
  addFirstBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  list: {
    paddingHorizontal: 22,
    paddingTop: 14,
    paddingBottom: 48,
  },
  card: {
    backgroundColor: "rgba(15,23,42,0.76)",
    borderRadius: 26,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.18)",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.24,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  cardGlow: {
    position: "absolute",
    top: -70,
    right: -70,
    width: 150,
    height: 150,
    borderRadius: 150,
    backgroundColor: "rgba(99,102,241,0.12)",
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  cardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    minWidth: 0,
  },
  vehicleIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.4)",
    backgroundColor: "rgba(99,102,241,0.14)",
  },
  vehicleTitleWrap: {
    flex: 1,
    minWidth: 0,
    marginLeft: 12,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: C.text,
  },
  cardSubtitle: {
    fontSize: 13,
    color: C.sub,
    marginTop: 2,
  },
  cardActions: {
    flexDirection: "row",
    gap: 8,
    marginLeft: 10,
  },
  actionBtn: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: "rgba(2,6,23,0.34)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.16)",
    justifyContent: "center",
    alignItems: "center",
  },
  cardBody: {
    gap: 10,
    paddingTop: 2,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 22,
  },
  infoLabel: {
    fontSize: 13,
    color: C.sub,
  },
  infoValue: {
    fontSize: 13,
    color: C.text,
    fontWeight: "800",
    flexShrink: 1,
  },
  notesRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  notesText: {
    flex: 1,
    fontSize: 13,
    color: C.sub,
    fontStyle: "italic",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#020617",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    maxHeight: "90%",
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.16)",
    overflow: "hidden",
  },
  modalHero: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(199,210,254,0.14)",
    overflow: "hidden",
  },
  modalHeroGlow: {
    position: "absolute",
    top: -82,
    right: -64,
    width: 180,
    height: 180,
    borderRadius: 180,
    backgroundColor: "rgba(129,140,248,0.18)",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 22,
    paddingVertical: 20,
    gap: 12,
  },
  modalTitleRow: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  modalIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.38)",
    backgroundColor: "rgba(99,102,241,0.14)",
  },
  modalCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.2)",
    backgroundColor: "rgba(2,6,23,0.36)",
  },
  modalTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 22,
    fontWeight: "900",
    color: C.text,
  },
  modalBody: {
    paddingHorizontal: 22,
    paddingTop: 18,
    maxHeight: 500,
  },
  formSection: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.14)",
    backgroundColor: "rgba(15,23,42,0.72)",
    padding: 16,
    marginBottom: 14,
  },
  formSectionTitle: {
    color: C.text,
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 10,
  },
  inputGroup: {
    marginBottom: 14,
  },
  inputRow: {
    flexDirection: "row",
    gap: 10,
  },
  inputHalf: {
    flex: 1,
    minWidth: 0,
  },
  label: {
    fontSize: 13,
    fontWeight: "800",
    color: C.sub,
    marginBottom: 8,
  },
  input: {
    backgroundColor: "rgba(2,6,23,0.34)",
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.16)",
    borderRadius: 18,
    padding: 14,
    color: C.text,
    fontSize: 16,
  },
  textArea: {
    height: 100,
    textAlignVertical: "top",
  },
  modalFooter: {
    flexDirection: "row",
    gap: 12,
    padding: 22,
    borderTopWidth: 1,
    borderTopColor: "rgba(199,210,254,0.12)",
    backgroundColor: "rgba(2,6,23,0.76)",
  },
  modalBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  modalBtnCancel: {
    backgroundColor: "rgba(15,23,42,0.74)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
  },
  modalBtnCancelText: {
    color: C.text,
    fontWeight: "700",
    fontSize: 16,
  },
  modalBtnSave: {
    backgroundColor: C.primary,
  },
  modalBtnSaveText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  picker: {
    backgroundColor: "rgba(2,6,23,0.34)",
    borderWidth: 1,
    borderColor: "rgba(199,210,254,0.16)",
    borderRadius: 18,
    padding: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  pickerText: {
    color: C.text,
    fontSize: 15,
  },
  pickerPlaceholder: {
    color: C.sub,
    fontSize: 15,
  },
  garageItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(148,163,184,0.15)",
  },
  garageName: {
    fontSize: 16,
    fontWeight: "700",
    color: C.text,
  },
  garageEmail: {
    fontSize: 13,
    color: C.sub,
    marginTop: 2,
  },
  statusRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(199,210,254,0.13)",
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  statusText: {
    fontSize: 13,
    fontWeight: "700",
  },
  statusButtons: {
    flexDirection: "row",
    gap: 7,
    flexShrink: 1,
  },
  statusBtn: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  statusBtnText: {
    fontSize: 12,
    fontWeight: "600",
  },
});

